// Armazém coletivo da nave: quantidades atômicas e histórico compartilhado.
const CATEGORIAS_INVENTARIO=['Equipamento','Ferramenta','Suprimento','Tecnologia','Documento','Artefato','Outro'];
let filtroInventarioV7={busca:'',categoria:''};
function telaInventario(){
    const items=(banco.inventario||[]).filter(i=>!i.arquivado);
    return `<section class="n-workspace" id="pagina-inventario"><div class="n-heading"><div><h2>Inventário da nave</h2><p>Armazém compartilhado da tripulação</p></div><div class="n-actions"><button type="button" onclick="NaveUI.run(this,()=>NaveDados.list('inventario',true))">Atualizar</button><button class="primary" type="button" onclick="abrirFormularioItem()" ${NaveDados.states.inventario!=='ready'?'disabled':''}>Adicionar item</button></div></div>${NaveUI.status('inventario')}${NaveUI.legacy()}<div class="n-stats"><div><strong>${items.length}</strong><small>Itens cadastrados</small></div><div><strong>${items.reduce((sum,i)=>sum+Number(i.quantidade),0)}</strong><small>Unidades em estoque</small></div></div><div class="n-toolbar"><label>Buscar item<input id="busca-inventario" type="search" placeholder="Nome ou descrição" value="${NaveUI.esc(filtroInventarioV7.busca)}" oninput="filtrarInventario()"></label><label>Categoria<select id="categoria-inventario" onchange="filtrarInventario()"><option value="">Todas</option>${CATEGORIAS_INVENTARIO.map(c=>`<option ${c===filtroInventarioV7.categoria?'selected':''}>${c}</option>`).join('')}</select></label></div><div id="lista-inventario">${renderizarListaInventario(itensFiltradosV7())}</div></section>`;
}
function inicializarPaginaInventario(){NaveDados.list('inventario').catch(()=>{});}
function itensFiltradosV7(){const q=filtroInventarioV7.busca.trim().toLocaleLowerCase('pt-BR');return (banco.inventario||[]).filter(i=>!i.arquivado&&(!filtroInventarioV7.categoria||i.categoria===filtroInventarioV7.categoria)&&(!q||`${i.nome} ${i.descricao}`.toLocaleLowerCase('pt-BR').includes(q)));}
function filtrarInventario(){filtroInventarioV7={busca:document.getElementById('busca-inventario')?.value||'',categoria:document.getElementById('categoria-inventario')?.value||''};const list=document.getElementById('lista-inventario');if(list)list.innerHTML=renderizarListaInventario(itensFiltradosV7());}
function renderizarListaInventario(items){if(!items.length)return '<div class="n-empty"><h3>Nenhum item encontrado</h3><p>Adicione um item ou ajuste os filtros.</p></div>';const ready=NaveDados.states.inventario==='ready';return `<div class="n-table-wrap"><table class="n-table"><thead><tr><th>Item</th><th>Categoria</th><th>Estoque</th><th>Ações</th></tr></thead><tbody>${items.map(i=>`<tr><td><strong>${NaveUI.esc(i.nome)}</strong><p>${NaveUI.esc(i.descricao)}</p>${i.item_catalogo_id?'<span class="n-badge">Equipamento do catálogo</span>':''}</td><td data-label="Categoria">${NaveUI.esc(i.categoria)}</td><td><div class="n-quantity"><button type="button" aria-label="Retirar uma unidade de ${NaveUI.esc(i.nome)}" onclick="alterarQuantidadeItem(${i.id},-1,this)" ${!ready||i.quantidade<=0?'disabled':''}>−</button><strong>${i.quantidade}</strong><button type="button" aria-label="Adicionar uma unidade de ${NaveUI.esc(i.nome)}" onclick="alterarQuantidadeItem(${i.id},1,this)" ${!ready||i.quantidade>=9999?'disabled':''}>+</button></div></td><td><div class="n-actions"><button type="button" onclick="abrirFormularioItem(buscarItemInventario(${i.id}))" ${!ready?'disabled':''}>Editar</button><button type="button" onclick="NaveUI.history('inventario',${i.id},'Movimentações do item')">Histórico</button><button type="button" onclick="solicitarExclusaoItem(${i.id})" ${!ready?'disabled':''}>Arquivar</button></div></td></tr>`).join('')}</tbody></table></div>`;}
function abrirFormularioItem(item=null){
    const current=item?{...item}:{};
    NaveUI.form(item?'Editar item':'Adicionar item',`<div class="n-fields"><label>Nome<input name="nome" maxlength="100" required value="${NaveUI.esc(item?.nome||'')}"></label><label>Categoria<select name="categoria">${CATEGORIAS_INVENTARIO.map(c=>`<option ${c===(item?.categoria||'Equipamento')?'selected':''}>${c}</option>`).join('')}</select></label><label>Quantidade<input name="quantidade" type="number" min="0" max="9999" step="1" required value="${item?.quantidade??1}"></label><label>Vincular a equipamento<select name="catalogo"><option value="">Sem vínculo</option>${(typeof CATALOGO_ITENS_APRIMORAMENTO!=='undefined'?CATALOGO_ITENS_APRIMORAMENTO:[]).map(i=>`<option value="${NaveUI.esc(i.id)}" ${i.id===item?.item_catalogo_id?'selected':''}>${NaveUI.esc(i.nome)}</option>`).join('')}</select></label><label class="wide">Descrição<textarea name="descricao" rows="3" maxlength="2000" required>${NaveUI.esc(item?.descricao||'')}</textarea></label></div><p class="n-note">O armazém é coletivo. Vincular um equipamento identifica o item; os equipamentos pessoais continuam na ficha de cada tripulante.</p>`,async form=>{await NaveDados.saveItem({...current,nome:form.elements.nome.value.trim(),categoria:form.elements.categoria.value,quantidade:Number(form.elements.quantidade.value),descricao:form.elements.descricao.value.trim(),item_catalogo_id:form.elements.catalogo.value||null});mostrarNotificacao('Item salvo no armazém da nave.');});
}
function alterarQuantidadeItem(id,delta,button){const item=buscarItemInventario(id);if(item)NaveUI.run(button,async()=>{await NaveDados.quantity(item,delta);});}
function solicitarExclusaoItem(id){const item=buscarItemInventario(id);if(!item)return;NaveUI.form('Arquivar item',`<p>Arquivar <strong>${NaveUI.esc(item.nome)}</strong>? Ele sairá do estoque ativo e seu histórico será preservado.</p>`,async()=>{await NaveDados.archiveItem(item);mostrarNotificacao('Item arquivado.');},'Arquivar');}
function buscarItemInventario(id){return banco.inventario.find(i=>Number(i.id)===Number(id));}
function abrirModalNovoItem(){abrirFormularioItem();}function abrirModalEditarItem(id){abrirFormularioItem(buscarItemInventario(id));}
function normalizarQuantidadeItem(v){return Math.max(0,Math.min(9999,Math.floor(Number(v)||0)));}
function escaparTextoInventario(v){return NaveUI.esc(v);}function escaparAtributoInventario(v){return NaveUI.esc(v);}
function obterIconeCategoriaInventario(c){return {'Equipamento':'🧰','Ferramenta':'🔧','Suprimento':'📦','Tecnologia':'💾','Documento':'📄','Artefato':'💎'}[c]||'◈';}
document.addEventListener('naveDadosAtualizados',e=>{if(e.detail.module==='inventario'&&typeof paginaAtual!=='undefined'&&paginaAtual==='inventario'){const content=document.getElementById('conteudo'),focus=document.activeElement,search=focus?.id==='busca-inventario',selection=search?focus.selectionStart:null;if(content){content.innerHTML=telaInventario();if(search){const input=document.getElementById('busca-inventario');input.focus();input.setSelectionRange(selection,selection);}}}});
