/* Cadastro de Kaijus. As cartas usam o mesmo formato executável do motor de combate. */
const KaijuEditor = (() => {
    let current=null, active='A', cards={}, pendingUpload=null, modal=null;
    const M=()=>CombateMotor, esc=v=>NaveUI.esc(v);
    const targets=[['auto','Primeiro adversário vivo'],['all','Todos os adversários'],['random','Aleatório'],['random2','Dois aleatórios'],['lowest','Menor vida'],['highest','Maior vida'],['left','Esquerda'],['right','Direita'],['middle','Meio'],['self','Próprio Kaiju']];
    function open(id=null, duplicate=false){
        const source=catalogoKaijusRegistro.find(k=>k.id===id);current=source?M().clone(source):{nome:'',vida:100,agilidade:5,defesa:0,descricao:'',codex_texto:'',passivas:'',imagem_path:'',ataques:{},regras_combate:{}};
        if(duplicate){current.nome+=' · cópia';delete current.id;delete current.versao;}
        cards={};active='A';pendingUpload=null;
        const codex=source?obterCodexKaiju(source.id):null;
        for(const c of M().CARDS){const a=(Object.keys(current.ataques||{}).length?current.ataques:codex?.ataques||{})[c];if(a){const parsed=M().parse(a.descricao||'',{boss:true});cards[c]={...parsed,...current.regras_combate?.[c],name:a.nome||'',text:a.descricao||'',damage:Number.isFinite(Number(a.dano))?Number(a.dano):0};if(!Number.isFinite(Number(a.dano))){cards[c].warnings.push('Dano composto: configure os golpes e efeitos antes de usar no combate.');cards[c].reviewed=false;}}}
        NaveUI.form(current.id?'Editar Kaiju':'Novo Kaiju',`<div class="ke-overview"><div class="ke-portrait" id="ke-preview">${imageMarkup(current.imagem_url||current.imagem_path)}</div><div class="n-fields"><label class="wide">Nome<input name="nome" maxlength="100" required value="${esc(current.nome)}"></label><label>Vida<input name="vida" type="number" min="1" max="1000000" required value="${current.vida||100}"></label><label>Agilidade<input name="agilidade" type="number" min="0" max="10000" required value="${current.agilidade??5}"></label><label>Defesa<input name="defesa" type="number" min="-10000" max="10000" required value="${current.defesa??0}"></label><label>Imagem<input id="ke-file" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="wide">URL da imagem<input id="ke-image-url" name="imagem" value="${esc(current.imagem_path||'')}" placeholder="https://…"></label></div></div><label>Descrição<textarea name="descricao" rows="2" maxlength="5000">${esc(current.descricao)}</textarea></label><details class="ke-lore"><summary>Codex e passivas</summary><label>Codex<textarea name="codex" rows="3" maxlength="10000">${esc(current.codex_texto||codex?.codex||'')}</textarea></label><label>Passivas<textarea name="passivas" rows="3" maxlength="5000">${esc(current.passivas)}</textarea></label><p class="n-note">Represente as passivas de combate nos atributos ou nos efeitos das cartas abaixo.</p></details><section class="ke-deck"><div class="n-heading"><div><h3>Cartas do chefe</h3><p class="n-note">Selecione uma carta para definir seu ataque.</p></div></div><div class="ke-tabs" role="tablist" aria-label="Cartas">${M().CARDS.map(c=>`<button type="button" role="tab" aria-selected="${c===active}" data-ke-card="${c}" class="${c===active?'active':''}">${c}<small>${cards[c]?'●':'—'}</small></button>`).join('')}</div><div id="ke-rule"></div></section>`,save,'Salvar Kaiju');
        modal=document.getElementById('n-form');modal.closest('.modal-ui').classList.add('ke-modal');renderCard();
        modal.addEventListener('click',e=>{const b=e.target.closest('[data-ke-card],[data-ke-action]');if(!b)return;if(b.dataset.keCard){storeCard();active=b.dataset.keCard;renderCard();modal.querySelectorAll('[data-ke-card]').forEach(x=>{x.classList.toggle('active',x.dataset.keCard===active);x.setAttribute('aria-selected',x.dataset.keCard===active);});}else if(b.dataset.keAction==='parse'){const old=readCard(), parsed=M().parse(old.text,{boss:true});cards[active]={...parsed,name:old.name||parsed.name};renderCard();}else if(b.dataset.keAction==='add'){storeCard();cards[active]||={...M().rule(),damage:0};cards[active].effects.push({kind:'stun',value:0,duration:1,chance:100,target:'target'});renderCard();}else if(b.dataset.keAction==='remove'){storeCard();cards[active].effects.splice(Number(b.dataset.index),1);renderCard();}});
        modal.querySelector('#ke-file').addEventListener('change',previewFile);
        modal.querySelector('#ke-image-url').addEventListener('change',e=>{document.getElementById('ke-preview').innerHTML=imageMarkup(e.target.value);});
        modal.addEventListener('input',e=>{if(e.target.id==='ke-text'){document.getElementById('ke-reviewed').checked=false;document.getElementById('ke-text-warning').hidden=false;}});
    }
    function imageMarkup(url){return /^(https?:\/\/|assets\/|blob:)/.test(url||'')?`<img src="${esc(url)}" alt="Imagem do Kaiju">`:'<div><span aria-hidden="true">◇</span><p>Imagem do chefe</p></div>';}
    function renderCard(){
        const r=cards[active]||{...M().rule(),damage:0};const selector=(items,value)=>items.concat(value&&!items.some(([id])=>id===value)?[[value,value]]:[]).map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
        document.getElementById('ke-rule').innerHTML=`<div class="ke-card-head"><strong>Carta ${active}</strong><span class="n-badge">${r.name?'Ataque cadastrado':'Sem ataque'}</span></div><div class="n-fields"><label>Nome do ataque<input id="ke-name" maxlength="100" value="${esc(r.name)}"></label><label>Dano base<input id="ke-damage" type="number" min="0" max="1000000" value="${r.damage||0}"></label><label class="wide">Descrição<textarea id="ke-text" rows="2" maxlength="5000" placeholder="Causa 5 de dano e atordoa o jogador da esquerda por 1 rodada">${esc(r.text)}</textarea></label></div><div class="n-actions"><button type="button" data-ke-action="parse">Interpretar descrição</button><span class="n-note" id="ke-text-warning" hidden>Texto alterado: confira a interpretação.</span></div><div class="n-fields"><label>Alvo<select id="ke-target">${selector(targets,r.target||'auto')}</select></label><label>Cura do Kaiju<input id="ke-heal" type="number" min="0" max="1000000" value="${r.heal||0}"></label></div><div class="ke-effects">${(r.effects||[]).map((e,i)=>`<div class="ke-effect" data-effect="${i}"><label>Efeito<select data-ke-field="kind">${selector(Object.entries(M().KINDS),e.kind)}</select></label><label>Valor<input data-ke-field="value" type="number" value="${e.value||0}"></label><label>Rodadas<input data-ke-field="duration" type="number" min="1" max="99" value="${e.duration||1}"></label><label>Chance %<input data-ke-field="chance" type="number" min="0" max="100" value="${e.chance??100}"></label><label>Aplicar em<select data-ke-field="target">${selector([['target','Alvo da carta'],['self','Próprio Kaiju']],e.target)}</select></label><button type="button" data-ke-action="remove" data-index="${i}" aria-label="Remover efeito">×</button></div>`).join('')}</div><button type="button" data-ke-action="add">+ Adicionar efeito</button>${r.warnings?.length?`<div class="n-state legacy">${r.warnings.map(esc).join(' ')}</div>`:''}<label class="n-check"><input id="ke-reviewed" type="checkbox" ${r.reviewed?'checked':''}>Conferi a regra, os alvos e a duração.</label>`;
    }
    function readCard(){const r=cards[active]||M().rule();const get=id=>document.getElementById(id);return {...r,name:get('ke-name').value.trim(),text:get('ke-text').value.trim(),damage:Number(get('ke-damage').value),heal:Number(get('ke-heal').value),target:get('ke-target').value,reviewed:get('ke-reviewed').checked,effects:[...modal.querySelectorAll('.ke-effect')].map((el,i)=>{const e={...r.effects?.[i]};for(const field of el.querySelectorAll('[data-ke-field]'))e[field.dataset.keField]=field.type==='number'?Number(field.value):field.value;return e;})};}
    function storeCard(){const r=readCard();if(!document.getElementById('ke-text-warning').hidden&&!r.reviewed){r.warnings=[...new Set([...(r.warnings||[]),'Descrição alterada: confira os campos antes de usar.'])];}if(r.name||r.text||r.damage||r.heal||r.effects.length)cards[active]=r;else delete cards[active];}
    async function previewFile(e){const file=e.target.files[0];if(!file)return;const err=document.getElementById('n-form-error');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>4000000){err.textContent='Use PNG, JPG ou WEBP até 4 MB.';e.target.value='';return;}if(pendingUpload?.preview)URL.revokeObjectURL(pendingUpload.preview);pendingUpload={file,preview:URL.createObjectURL(file)};document.getElementById('ke-preview').innerHTML=imageMarkup(pendingUpload.preview);}
    async function save(form){
        storeCard();const fields=form.elements;const attacks={};for(const [c,r]of Object.entries(cards)){if(!r.reviewed&&(r.text||r.effects.length))throw Error(`Confira a interpretação da carta ${c} antes de salvar.`);attacks[c]={nome:r.name||'Efeito',dano:r.damage,descricao:r.text};}
        const state=M().create({teams:[{id:'validacao',name:'Frota',players:[{id:'alvo',name:'Jogador',maxHp:20}]}],boss:{id:'boss',name:fields.nome.value,cards}});M().validate(state);
        const record=M().clone(current),rules=M().clone(cards),file=pendingUpload?.file;
        const payload={nome:fields.nome.value.trim(),vida:Number(fields.vida.value),agilidade:Number(fields.agilidade.value),defesa:Number(fields.defesa.value),descricao:fields.descricao.value,codex_texto:fields.codex.value,passivas:fields.passivas.value,ataques:attacks,regras_combate:rules};
        let uploaded=null;const imagePath=fields.imagem.value.trim();
        if(imagePath&&!/^(https?:\/\/|assets\/)/.test(imagePath))throw Error('Use uma URL de imagem válida ou envie um arquivo.');
        try {
            const changedUrl=imagePath!==(record.imagem_path||'');let source=changedUrl?null:record.imagem_storage;
            if(file){uploaded=await NaveDados.uploadKaiju(file);source=uploaded;}
            await NaveDados.request('nave_salvar_kaiju',{p_id:record.id||null,p_versao:record.versao??null,p_dados:{...payload,imagem_path:imagePath,imagem_storage:source||null}});
        }catch(e){if(uploaded)await NaveDados.removeUpload(uploaded);throw e;}
        if(form===modal&&pendingUpload?.preview){URL.revokeObjectURL(pendingUpload.preview);pendingUpload=null;}
        await carregarRegistroKaijus();mostrarNotificacao('Kaiju salvo. Ele já está disponível na preparação do combate.');
    }
    document.addEventListener('modalFechado',()=>{if(pendingUpload?.preview)URL.revokeObjectURL(pendingUpload.preview);pendingUpload=null;});
    return {open};
})();
