// Sistema estelar compartilhado. Toda escrita passa pelas funções do Supabase.
let planetaSelecionado = null;
function telaMapa() {
    const planets=banco.planetas||[], chosen=planets.find(p=>p.id===planetaSelecionado)||planets[0];
    if(chosen)planetaSelecionado=chosen.id;
    return `<section class="n-workspace" id="pagina-mapa"><div class="n-heading"><div><h2>Sistema Estelar</h2><p>${planets.filter(p=>p.desbloqueado).length} de ${planets.length} destinos disponíveis</p></div><div class="n-actions"><button type="button" onclick="NaveUI.run(this,()=>NaveDados.list('planetas',true))">Atualizar</button><button class="primary" type="button" onclick="abrirFormularioPlaneta()" ${NaveDados.states.planetas!=='ready'?'disabled':''}>Novo planeta</button></div></div>${NaveUI.status('planetas')}${NaveUI.legacy()}<div class="n-planets"><div class="n-planet-list" aria-label="Planetas">${planets.map(p=>`<button type="button" class="${p.id===chosen?.id?'active':''}" onclick="selecionarPlanetaMapa(${p.id})" aria-pressed="${p.id===chosen?.id}"><span class="n-planet-symbol" aria-hidden="true">${p.desbloqueado?'◉':'◇'}</span><span><strong>${NaveUI.esc(p.desbloqueado?p.nome:'Incógnita')}</strong><small>${p.desbloqueado?'Exploração liberada':'Aguardando liberação'}</small></span></button>`).join('')}</div><aside id="painel-planeta" class="n-panel n-planet-detail">${chosen?renderizarPlanetaV7(chosen):'<div class="n-empty"><h3>Destinos da nave</h3><p>Os planetas aparecem aqui após a sincronização.</p></div>'}</aside></div></section>`;
}
function inicializarPaginaMapa(){NaveDados.list('planetas').catch(()=>{});}
function renderizarPlanetaV7(p){
    const missions=(banco.missoes||[]).filter(m=>Number(m.planetaId)===Number(p.id));
    const ready=NaveDados.states.planetas==='ready';
    return `<div class="n-heading"><div><span class="n-badge ${p.desbloqueado?'open':''}">${p.desbloqueado?'Disponível':'Bloqueado'}</span><h3>${NaveUI.esc(p.desbloqueado?p.nome:'Planeta incógnito')}</h3></div><span class="n-note">Destino ${String(p.id).padStart(2,'0')}</span></div><p>${NaveUI.esc(p.desbloqueado?p.descricao:'Libere este destino quando suas informações forem reveladas à tripulação.')}</p><div class="n-stats"><div><strong>${missions.length}</strong><small>Missões</small></div><div><strong>${missions.filter(m=>m.status==='Concluída').length}</strong><small>Concluídas por você</small></div></div><div class="n-actions">${p.desbloqueado?`<button type="button" onclick="filtroPlanetaMissao='${p.id}';abrirPagina('missoes')">Ver missões</button>`:''}<button class="primary" type="button" onclick="abrirFormularioPlaneta(${p.id},${!p.desbloqueado})" ${!ready?'disabled':''}>${p.desbloqueado?'Editar informações':'Liberar destino'}</button>${p.id!==1&&p.desbloqueado?`<button type="button" onclick="solicitarBloqueioPlaneta(${p.id})" ${!ready?'disabled':''}>Bloquear</button>`:''}<button type="button" onclick="NaveUI.history('planetas',${p.id},'Histórico do planeta')">Histórico</button></div>${p.id===1?'<p class="n-note">Verdejante é o destino inicial e permanece disponível.</p>':''}<p class="n-note">${p.atualizado_em?'Atualizado em '+NaveUI.date(p.atualizado_em):''}</p>`;
}
function selecionarPlanetaMapa(id){planetaSelecionado=Number(id);atualizarMapaV7();}
function atualizarMapaV7(){if(typeof paginaAtual!=='undefined'&&paginaAtual==='mapa'){const area=document.getElementById('conteudo');if(area)area.innerHTML=telaMapa();}}
function abrirFormularioPlaneta(id=null,unlock=false){
    const p=(banco.planetas||[]).find(p=>p.id===id); const existing=p?{...p}:{};
    NaveUI.form(p?(unlock?'Liberar destino':'Editar planeta'):'Novo planeta',`<label>Nome<input name="nome" maxlength="80" required value="${NaveUI.esc(p?.nome||'')}"></label><label>Descrição<textarea name="descricao" rows="4" maxlength="2000" required>${NaveUI.esc(p?.descricao||'')}</textarea></label><label class="n-check"><input name="disponivel" type="checkbox" ${unlock||p?.desbloqueado?'checked':''} ${id===1?'disabled':''}>Disponível para exploração</label>`,async form=>{const saved=await NaveDados.savePlanet({...existing,nome:form.elements.nome.value.trim(),descricao:form.elements.descricao.value.trim(),desbloqueado:id===1||form.elements.disponivel.checked});planetaSelecionado=saved.id;atualizarMapaV7();mostrarNotificacao('Planeta salvo para toda a tripulação.');});
}
function solicitarBloqueioPlaneta(id){const p=banco.planetas.find(p=>p.id===id);if(!p||id===1)return;NaveUI.form('Bloquear destino',`<p>Bloquear o acesso a <strong>${NaveUI.esc(p.nome)}</strong>? As missões e o histórico serão mantidos.</p>`,async()=>{await NaveDados.savePlanet({...p,desbloqueado:false});mostrarNotificacao('Destino bloqueado.');},'Bloquear destino');}
function buscarPlanetaMapa(id){return banco.planetas.find(p=>Number(p.id)===Number(id));}
function obterIconePlaneta(p){return p.desbloqueado?'◉':'◇';}
function garantirEstruturaPlanetas(){if(!Array.isArray(banco.planetas))banco.planetas=[];}
function escaparTextoMapa(v){return NaveUI.esc(v);}function escaparAtributoMapa(v){return NaveUI.esc(v);}
document.addEventListener('naveDadosAtualizados',e=>{if(e.detail.module==='planetas')atualizarMapaV7();});
