-- Novos itens: Espólios de Gelo e Cristal
-- Execute no SQL Editor do Supabase para também registrar os itens no catálogo remoto.

insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('garras-urso-penguin','Garras de Urso Penguin',27,'{"id":"garras-urso-penguin","nome":"Garras de Urso Penguin","origem":"Urso Penguin","cartas":[1,2,3,4],"dano":30,"tipo":"Arma","descricao":"Dano Constante: uma arma rápida e confiável. Causa 30 de dano direto."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('capa-urso-penguin','Capa de Urso Penguin',28,'{"id":"capa-urso-penguin","nome":"Capa de Urso Penguin","origem":"Urso Penguin","cartas":["Q"],"dano":0,"tipo":"Defensivo","descricao":"Barreira Glacial: ao ativar, você ganha um Escudo de Gelo. O material informa que ele concede 10 * embaixador. O escudo não se acumula se usado duas vezes seguidas."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('machado-urso-penguin','Machado do Urso Penguin',29,'{"id":"machado-urso-penguin","nome":"Machado do Urso Penguin","origem":"Urso Penguin","cartas":[1,5,10],"dano":15,"tipo":"Arma Condicional","danoDinamico":true,"descricao":"Combo Brutal: causa 15 de dano base + o valor exato de dano do seu ataque anterior."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('espada-penguin-escudo-urso','Espada do Penguin e Escudo do Urso',30,'{"id":"espada-penguin-escudo-urso","nome":"Espada do Penguin e Escudo do Urso","origem":"Urso Penguin","cartas":[],"dano":0,"tipo":"Arma Especial Rara","cartasConfiguraveis":3,"danoDinamico":true,"descricao":"Ativação: escolha 3 números do seu baralho para abrigar esta arma. Golpe de Memória: causa 10 + o maior dano único que você já causou nesta batalha. Foco de Provocação: transforma dano em área que atingiria o time em dano individual focado em você e absorve 50% desse dano, exceto dano verdadeiro."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('alabarda-cristal','Alabarda de Cristal',31,'{"id":"alabarda-cristal","nome":"Alabarda de Cristal","origem":"Aranha de Cristal","cartas":[2,4,6,7],"dano":20,"tipo":"Arma / Suporte","descricao":"Suporte Ofensivo: causa 20 de dano e cura 10 HP do jogador que estiver com a vida mais baixa no momento."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('rede-cristal','Rede de Cristal',32,'{"id":"rede-cristal","nome":"Rede de Cristal","origem":"Aranha de Cristal","cartas":["J"],"dano":0,"tipo":"Suporte","descricao":"Desarmar: escolha e remova permanentemente uma carta de ataque padrão (1 a 10) da ficha do inimigo. Aquele ataque não pode mais ser usado."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('faca-cristalina','Faca Cristalina',33,'{"id":"faca-cristalina","nome":"Faca Cristalina","origem":"Aranha de Cristal","cartas":[3,8,9],"dano":20,"tipo":"Arma","descricao":"Vampirismo: causa 20 de dano e cura o seu Mecha em uma quantidade de HP igual ao dano causado."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('oito-adagas-cristal','8 Adagas de Cristal',34,'{"id":"oito-adagas-cristal","nome":"8 Adagas de Cristal","origem":"Aranha de Cristal","cartas":[],"dano":15,"tipo":"Arma Especial Rara","cartasConfiguraveis":4,"danoDinamico":true,"descricao":"Ativação: escolha 4 números do seu baralho para abrigar esta arma. Ataque Base: 15 de dano. Estilhaçar Crítico: 50% de chance de acerto crítico; se ativado, causa entre 1 e 100 de dano extra."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
