-- Nave 3B V7. Executar sobre a V6. Sem recriar catálogos, apagar fichas ou recalcular missões.
begin;
create table if not exists public.nave_itens_catalogo (
 id text primary key, nome text not null, ordem integer not null,
 definicao jsonb not null check(jsonb_typeof(definicao)='object'), atualizado_em timestamptz not null default now()
);
create table if not exists public.nave_planetas (
 id bigint generated by default as identity primary key,
 nome text not null check(length(trim(nome)) between 1 and 80),
 descricao text not null default '' check(length(descricao)<=2000),
 desbloqueado boolean not null default false, ordem integer not null default 0,
 versao integer not null default 0, criado_por uuid references auth.users(id) on delete set null,
 atualizado_por uuid references auth.users(id) on delete set null,
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(),
 check(id<>1 or desbloqueado)
);
insert into public.nave_planetas(id,nome,descricao,desbloqueado,ordem) values
 (1,'Verdejante','Primeiro planeta disponível para exploração.',true,1),
 (2,'Incógnita','Dados ainda não revelados.',false,2),
 (3,'Incógnita','Dados ainda não revelados.',false,3),
 (4,'Incógnita','Dados ainda não revelados.',false,4)
on conflict(id) do nothing;
select setval(pg_get_serial_sequence('public.nave_planetas','id'),greatest((select coalesce(max(id),4) from public.nave_planetas),4),true);
-- Vínculo estável para novas automações; o texto de planeta das missões é preservado.
alter table if exists public.missoes_catalogo add column if not exists planeta_id bigint references public.nave_planetas(id) on delete restrict;
do $$ begin
 if to_regclass('public.missoes_catalogo') is not null then
  update public.missoes_catalogo m set planeta_id=p.id from public.nave_planetas p
  where m.planeta_id is null and lower(trim(m.planeta))=lower(trim(p.nome))
   and (select count(*) from public.nave_planetas n where lower(trim(n.nome))=lower(trim(p.nome)))=1;
 end if;
end $$;

create table if not exists public.nave_inventario (
 id bigint generated always as identity primary key,
 nome text not null check(length(trim(nome)) between 1 and 100),
 categoria text not null check(categoria in ('Equipamento','Ferramenta','Suprimento','Tecnologia','Documento','Artefato','Outro')),
 quantidade integer not null default 0 check(quantidade between 0 and 9999),
 descricao text not null default '' check(length(descricao)<=2000),
 item_catalogo_id text references public.nave_itens_catalogo(id) on delete restrict,
 arquivado boolean not null default false, versao integer not null default 0,
 criado_por uuid references auth.users(id) on delete set null,
 atualizado_por uuid references auth.users(id) on delete set null,
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create unique index if not exists nave_inventario_nome on public.nave_inventario(lower(trim(nome)));
create table if not exists public.nave_eventos (
 id bigint generated always as identity primary key,
 modulo text not null, registro_id text not null, acao text not null,
 autor_id uuid references auth.users(id) on delete set null, autor_nome text not null default 'Tripulante',
 resumo text not null, dados jsonb not null default '{}', criado_em timestamptz not null default now()
);
create index if not exists nave_eventos_registro on public.nave_eventos(modulo,registro_id,id desc);
create table if not exists public.nave_operacoes (
 usuario_id uuid not null references auth.users(id) on delete cascade,
 chave text not null, resultado jsonb not null, criado_em timestamptz not null default now(),
 primary key(usuario_id,chave)
);
create table if not exists public.kaiju_rolagens (
 id bigint generated always as identity primary key,
 usuario_id uuid not null references auth.users(id) on delete cascade,
 kaiju_id text not null references public.mecha_kaijus_catalogo(id) on delete restrict,
 carta text not null, ataque jsonb not null, criado_em timestamptz not null default now()
);
create index if not exists kaiju_rolagens_usuario on public.kaiju_rolagens(usuario_id,kaiju_id,id desc);
alter table public.mecha_kaijus_catalogo
 add column if not exists vida integer not null default 0,
 add column if not exists agilidade integer not null default 0,
 add column if not exists defesa integer not null default 0,
 add column if not exists passivas text not null default '',
 add column if not exists codex_texto text not null default '',
 add column if not exists ataques jsonb not null default '{}',
 add column if not exists regras_combate jsonb not null default '{}',
 add column if not exists imagem_storage jsonb,
 add column if not exists personalizado boolean not null default false,
 add column if not exists criado_por uuid references auth.users(id) on delete set null,
 add column if not exists versao integer not null default 0,
 add column if not exists atualizado_em timestamptz not null default now();

alter table public.nave_itens_catalogo enable row level security;
alter table public.nave_planetas enable row level security;
alter table public.nave_inventario enable row level security;
alter table public.nave_eventos enable row level security;
alter table public.nave_operacoes enable row level security;
alter table public.kaiju_rolagens enable row level security;
do $$ declare t text; begin
 foreach t in array array['nave_itens_catalogo','nave_planetas','nave_inventario','nave_eventos'] loop
  execute format('drop policy if exists leitura_nave on public.%I',t);
  execute format('create policy leitura_nave on public.%I for select to authenticated using(true)',t);
  execute format('grant select on public.%I to authenticated',t);
  execute format('revoke insert,update,delete on public.%I from anon,authenticated',t);
 end loop;
end $$;
revoke all on public.nave_operacoes from anon,authenticated;
revoke insert,update,delete on public.kaiju_rolagens from anon,authenticated;
grant select on public.kaiju_rolagens to authenticated;
drop policy if exists minhas_rolagens on public.kaiju_rolagens;
create policy minhas_rolagens on public.kaiju_rolagens for select to authenticated using(usuario_id=auth.uid());

create or replace function public.nave_registrar_evento(p_modulo text,p_id text,p_acao text,p_resumo text,p_dados jsonb default '{}') returns void
language plpgsql security definer set search_path=public as $$
declare nome_autor text;
begin
 select coalesce(nullif(nome,''),username,'Tripulante') into nome_autor from public.profiles where id=auth.uid();
 insert into public.nave_eventos(modulo,registro_id,acao,autor_id,autor_nome,resumo,dados)
 values(p_modulo,p_id,p_acao,auth.uid(),coalesce(nome_autor,'Tripulante'),p_resumo,p_dados);
end $$;
revoke all on function public.nave_registrar_evento(text,text,text,text,jsonb) from public,anon,authenticated;

create or replace function public.nave_salvar_planeta(p_id bigint,p_versao integer,p_dados jsonb) returns jsonb
language plpgsql security definer set search_path=public as $$
declare anterior public.nave_planetas; novo public.nave_planetas;
begin
 if auth.uid() is null then raise exception 'Entre na sua conta'; end if;
 if jsonb_typeof(p_dados) is distinct from 'object' then raise exception 'Dados inválidos'; end if;
 if p_id is null then
  insert into public.nave_planetas(nome,descricao,desbloqueado,criado_por,atualizado_por)
  values(trim(p_dados->>'nome'),coalesce(p_dados->>'descricao',''),coalesce((p_dados->>'desbloqueado')::boolean,false),auth.uid(),auth.uid()) returning * into novo;
  update public.nave_planetas set ordem=novo.id,versao=1 where id=novo.id returning * into novo;
 else
  select * into anterior from public.nave_planetas where id=p_id for update;
  if not found then raise exception 'Planeta não encontrado'; end if;
  if anterior.versao is distinct from p_versao then raise exception 'Outra pessoa alterou este planeta. Atualize a lista e revise antes de salvar.'; end if;
  update public.nave_planetas set nome=trim(p_dados->>'nome'),descricao=coalesce(p_dados->>'descricao',''),desbloqueado=case when id=1 then true else coalesce((p_dados->>'desbloqueado')::boolean,false) end,
   versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now() where id=p_id returning * into novo;
 end if;
 perform public.nave_registrar_evento('planetas',novo.id::text,case when p_id is null then 'criar' else 'editar' end,'Destino '||novo.nome||case when novo.desbloqueado then ' disponível' else ' bloqueado' end,jsonb_build_object('anterior',to_jsonb(anterior),'posterior',to_jsonb(novo)));
 return to_jsonb(novo);
end $$;

create or replace function public.nave_salvar_item(p_id bigint,p_versao integer,p_dados jsonb) returns jsonb
language plpgsql security definer set search_path=public as $$
declare anterior public.nave_inventario; novo public.nave_inventario;
begin
 if auth.uid() is null then raise exception 'Entre na sua conta'; end if;
 if jsonb_typeof(p_dados) is distinct from 'object' then raise exception 'Dados inválidos'; end if;
 if p_id is null then
  insert into public.nave_inventario(nome,categoria,quantidade,descricao,item_catalogo_id,criado_por,atualizado_por)
  values(trim(p_dados->>'nome'),p_dados->>'categoria',(p_dados->>'quantidade')::integer,coalesce(p_dados->>'descricao',''),nullif(p_dados->>'item_catalogo_id',''),auth.uid(),auth.uid()) returning * into novo;
 else
  select * into anterior from public.nave_inventario where id=p_id and not arquivado for update;
  if not found then raise exception 'Item indisponível'; end if;
  if anterior.versao is distinct from p_versao then raise exception 'O estoque foi alterado por outra pessoa. Atualize a lista antes de salvar.'; end if;
  update public.nave_inventario set nome=trim(p_dados->>'nome'),categoria=p_dados->>'categoria',quantidade=(p_dados->>'quantidade')::integer,descricao=coalesce(p_dados->>'descricao',''),item_catalogo_id=nullif(p_dados->>'item_catalogo_id',''),versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now() where id=p_id returning * into novo;
 end if;
 perform public.nave_registrar_evento('inventario',novo.id::text,case when p_id is null then 'criar' else 'editar' end,novo.nome||': '||novo.quantidade||' unidade(s)',jsonb_build_object('anterior',to_jsonb(anterior),'posterior',to_jsonb(novo)));
 return to_jsonb(novo);
end $$;

create or replace function public.nave_movimentar_item(p_id bigint,p_delta integer,p_operacao uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare item public.nave_inventario; resultado jsonb; chave_op text;
begin
 if auth.uid() is null or p_operacao is null then raise exception 'Operação inválida'; end if;
 if p_delta is null or p_delta not in (-1,1) then raise exception 'Informe entrada ou retirada de uma unidade'; end if;
 chave_op:='estoque:'||p_operacao;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||chave_op,0));
 select o.resultado into resultado from public.nave_operacoes o where usuario_id=auth.uid() and chave=chave_op;
 if found then return resultado; end if;
 select * into item from public.nave_inventario where id=p_id and not arquivado for update;
 if not found then raise exception 'Item indisponível'; end if;
 if item.quantidade+p_delta not between 0 and 9999 then raise exception 'Estoque insuficiente ou limite de 9999 unidades atingido'; end if;
 update public.nave_inventario set quantidade=quantidade+p_delta,versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now() where id=p_id returning * into item;
 resultado:=to_jsonb(item);
 perform public.nave_registrar_evento('inventario',p_id::text,'movimentar',case when p_delta>0 then 'Entrada: ' else 'Retirada: ' end||'1 '||item.nome||' · saldo '||item.quantidade,jsonb_build_object('delta',p_delta,'saldo',item.quantidade));
 insert into public.nave_operacoes values(auth.uid(),chave_op,resultado,now()); return resultado;
end $$;

create or replace function public.nave_arquivar_item(p_id bigint,p_versao integer) returns jsonb
language plpgsql security definer set search_path=public as $$
declare item public.nave_inventario;
begin
 if auth.uid() is null then raise exception 'Entre na sua conta'; end if;
 select * into item from public.nave_inventario where id=p_id for update;
 if not found or item.versao is distinct from p_versao then raise exception 'Item alterado. Atualize a lista.'; end if;
 update public.nave_inventario set arquivado=true,versao=versao+1,atualizado_por=auth.uid(),atualizado_em=now() where id=p_id returning * into item;
 perform public.nave_registrar_evento('inventario',p_id::text,'arquivar','Item arquivado: '||item.nome); return to_jsonb(item);
end $$;

create or replace function public.nave_importar_legado(p_chave text,p_planetas jsonb,p_itens jsonb) returns jsonb
language plpgsql security definer set search_path=public as $$
declare resultado jsonb; entry jsonb; item public.nave_inventario; planeta public.nave_planetas; ni integer:=0; np integer:=0; skip integer:=0;
begin
 if auth.uid() is null or coalesce(length(p_chave),0) not between 1 and 100 then raise exception 'Importação inválida'; end if;
 if jsonb_typeof(p_planetas) is distinct from 'array' or jsonb_typeof(p_itens) is distinct from 'array' or jsonb_array_length(p_itens)>1000 or jsonb_array_length(p_planetas)>1000 then raise exception 'Registros inválidos'; end if;
 perform pg_advisory_xact_lock(hashtextextended('nave:importacao',0));
 select o.resultado into resultado from public.nave_operacoes o where usuario_id=auth.uid() and chave='legado:'||p_chave;
 if found then return resultado; end if;
 for entry in select value from jsonb_array_elements(p_itens) loop
  if length(trim(coalesce(entry->>'nome',''))) not between 1 and 100 then skip:=skip+1; continue; end if;
  if exists(select 1 from public.nave_inventario where lower(trim(nome))=lower(trim(entry->>'nome'))) then skip:=skip+1; continue; end if;
  insert into public.nave_inventario(nome,categoria,quantidade,descricao,criado_por,atualizado_por)
   values(trim(entry->>'nome'),case when entry->>'categoria' in ('Equipamento','Ferramenta','Suprimento','Tecnologia','Documento','Artefato','Outro') then entry->>'categoria' else 'Outro' end,
    greatest(0,least(9999,coalesce((entry->>'quantidade')::numeric,0)))::integer,left(coalesce(entry->>'descricao',''),2000),auth.uid(),auth.uid()) returning * into item;
  perform public.nave_registrar_evento('inventario',item.id::text,'importar','Importado do navegador: '||item.nome); ni:=ni+1;
 end loop;
 for entry in select value from jsonb_array_elements(p_planetas) loop
  select * into planeta from public.nave_planetas where id=(entry->>'id')::bigint for update;
  if found and planeta.versao=0 and (coalesce((entry->>'desbloqueado')::boolean,false) or planeta.id=1) then
   update public.nave_planetas set nome=left(coalesce(nullif(trim(entry->>'nome'),''),nome),80),descricao=left(coalesce(entry->>'descricao',descricao),2000),desbloqueado=true,versao=1,atualizado_por=auth.uid(),atualizado_em=now() where id=planeta.id;
   perform public.nave_registrar_evento('planetas',planeta.id::text,'importar','Informações importadas do navegador'); np:=np+1;
  elsif not found and coalesce((entry->>'desbloqueado')::boolean,false) then
   perform public.nave_salvar_planeta(null,null,entry); np:=np+1;
  else skip:=skip+1; end if;
 end loop;
 resultado:=jsonb_build_object('itens',ni,'planetas',np,'ignorados',skip);
 insert into public.nave_operacoes values(auth.uid(),'legado:'||p_chave,resultado,now()); return resultado;
end $$;

create or replace function public.nave_salvar_kaiju(p_id text,p_versao integer,p_dados jsonb) returns jsonb
language plpgsql security definer set search_path=public as $$
declare registro public.mecha_kaijus_catalogo; proxima_ordem integer; id_novo text; carta text; ataque jsonb; regra jsonb; efeito jsonb; campo text;
begin
 if auth.uid() is null then raise exception 'Entre na sua conta'; end if;
 if jsonb_typeof(p_dados) is distinct from 'object' or octet_length(p_dados::text)>300000 then raise exception 'Registro inválido'; end if;
 if coalesce(length(trim(p_dados->>'nome')),0) not between 1 and 100 or coalesce((p_dados->>'vida')::integer,0) not between 1 and 1000000 or coalesce((p_dados->>'agilidade')::integer,-1) not between 0 and 10000 or coalesce((p_dados->>'defesa')::integer,-10001) not between -10000 and 10000 then raise exception 'Confira nome, vida, agilidade e defesa'; end if;
 if length(coalesce(p_dados->>'descricao',''))>5000 or length(coalesce(p_dados->>'codex_texto',''))>10000 or length(coalesce(p_dados->>'passivas',''))>5000 then raise exception 'Descrição muito longa'; end if;
 if jsonb_typeof(p_dados->'ataques') is distinct from 'object' or jsonb_typeof(p_dados->'regras_combate') is distinct from 'object' then raise exception 'Confira as cartas'; end if;
 if exists(select 1 from jsonb_object_keys(p_dados->'ataques') k where k not in ('A','2','3','4','5','6','7','8','9','10','J','Q','K')) then raise exception 'Carta inválida'; end if;
 -- O formato salvo também é validado aqui para futuros clientes e automações.
 if exists(select 1 from jsonb_object_keys(p_dados->'regras_combate') k where not (p_dados->'ataques')?k) then raise exception 'Regra sem carta correspondente'; end if;
 for carta,ataque in select key,value from jsonb_each(p_dados->'ataques') loop
  regra:=p_dados->'regras_combate'->carta;
  if jsonb_typeof(ataque) is distinct from 'object' or jsonb_typeof(regra) is distinct from 'object' then raise exception 'Carta % sem regra estruturada',carta; end if;
  if jsonb_typeof(ataque->'dano') is distinct from 'number' or jsonb_typeof(regra->'damage') is distinct from 'number' or (ataque->>'dano')::numeric is distinct from (regra->>'damage')::numeric then raise exception 'Confira o dano da carta %',carta; end if;
  foreach campo in array array['damage','heal','cost','choiceDamage','multiplier'] loop
   if regra?campo and (jsonb_typeof(regra->campo) is distinct from 'number' or (regra->>campo)::numeric not between 0 and 1000000) then raise exception 'Valor inválido na carta %: %',carta,campo; end if;
  end loop;
  if coalesce(regra->>'target','auto') not in ('auto','all','random','random2','lowest','highest','left','right','middle','self') and coalesce(regra->>'target','') !~ '^name:.{1,100}$' then raise exception 'Alvo inválido na carta %',carta; end if;
  if jsonb_typeof(regra->'effects') is distinct from 'array' or jsonb_array_length(regra->'effects')>40 then raise exception 'Confira os efeitos da carta %',carta; end if;
  for efeito in select value from jsonb_array_elements(regra->'effects') loop
   if jsonb_typeof(efeito) is distinct from 'object' or coalesce(efeito->>'kind','') not in ('stun','poison','burn','bleed','attack','defense','speed','shield','protection','weakness','blind','regen','healing','reflect','evasion','skip','haste') then raise exception 'Efeito inválido na carta %',carta; end if;
   if coalesce((efeito->>'duration')::numeric,0) not between 1 and 99 or coalesce((efeito->>'chance')::numeric,100) not between 0 and 100 or coalesce((efeito->>'value')::numeric,0) not between -1000000 and 1000000 then raise exception 'Confira duração, chance e valor da carta %',carta; end if;
   if coalesce(efeito->>'target','target') not in ('target','self','allies','boss') and coalesce(efeito->>'target','') !~ '^name:.{1,100}$' then raise exception 'Alvo do efeito inválido na carta %',carta; end if;
  end loop;
 end loop;
 if p_dados->'imagem_storage' is not null and p_dados->'imagem_storage'<>'null'::jsonb then
  if p_dados->'imagem_storage'->>'bucket' is distinct from 'kaijus-imagens' or split_part(p_dados->'imagem_storage'->>'path','/',1) is distinct from auth.uid()::text then
   -- Ao duplicar, uma referência de imagem já cadastrada pode ser reutilizada.
   if not exists(select 1 from public.mecha_kaijus_catalogo where imagem_storage=p_dados->'imagem_storage') then raise exception 'Referência de imagem inválida'; end if;
  end if;
 end if;
 if p_id is null then
  perform pg_advisory_xact_lock(hashtextextended('nave:cadastro-kaiju',0));
  select coalesce(max(ordem),0)+1 into proxima_ordem from public.mecha_kaijus_catalogo;
  id_novo:='kaiju-'||gen_random_uuid();
  insert into public.mecha_kaijus_catalogo(id,nome,ordem,imagem_path,descricao,vida,agilidade,defesa,passivas,codex_texto,ataques,regras_combate,imagem_storage,personalizado,criado_por,versao)
  values(id_novo,trim(p_dados->>'nome'),proxima_ordem,coalesce(p_dados->>'imagem_path',''),coalesce(p_dados->>'descricao',''),(p_dados->>'vida')::integer,(p_dados->>'agilidade')::integer,(p_dados->>'defesa')::integer,coalesce(p_dados->>'passivas',''),coalesce(p_dados->>'codex_texto',''),p_dados->'ataques',p_dados->'regras_combate',nullif(p_dados->'imagem_storage','null'::jsonb),true,auth.uid(),1) returning * into registro;
 else
  select * into registro from public.mecha_kaijus_catalogo where id=p_id for update;
  if not found or not registro.personalizado or registro.criado_por is distinct from auth.uid() then raise exception 'Você pode editar seus próprios Kaijus. Use Duplicar para adaptar um registro do catálogo.'; end if;
  if registro.versao is distinct from p_versao then raise exception 'Este Kaiju mudou em outra aba. Atualize o registro antes de salvar.'; end if;
  update public.mecha_kaijus_catalogo set nome=trim(p_dados->>'nome'),imagem_path=coalesce(p_dados->>'imagem_path',''),descricao=coalesce(p_dados->>'descricao',''),vida=(p_dados->>'vida')::integer,agilidade=(p_dados->>'agilidade')::integer,defesa=(p_dados->>'defesa')::integer,passivas=coalesce(p_dados->>'passivas',''),codex_texto=coalesce(p_dados->>'codex_texto',''),ataques=p_dados->'ataques',regras_combate=p_dados->'regras_combate',imagem_storage=nullif(p_dados->'imagem_storage','null'::jsonb),versao=versao+1,atualizado_em=now() where id=p_id returning * into registro;
 end if;
 perform public.nave_registrar_evento('kaijus',registro.id,case when p_id is null then 'criar' else 'editar' end,'Registro de '||registro.nome||' salvo',jsonb_build_object('versao',registro.versao,'cartas',(select count(*) from jsonb_object_keys(registro.ataques))));
 return to_jsonb(registro);
end $$;

create or replace function public.nave_sortear_ataque(p_kaiju_id text,p_operacao uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare escolha record; resultado jsonb; chave_op text;
begin
 if auth.uid() is null or p_operacao is null then raise exception 'Entre na sua conta'; end if;
 chave_op:='kaiju:'||p_operacao;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||chave_op,0));
 select o.resultado into resultado from public.nave_operacoes o where usuario_id=auth.uid() and chave=chave_op;
 if found then return resultado; end if;
 select a.key as carta,a.value as ataque into escolha from public.mecha_kaijus_catalogo k cross join lateral jsonb_each(k.ataques) a where k.id=p_kaiju_id order by random() limit 1;
 if not found then raise exception 'Este Kaiju ainda não possui ataques cadastrados'; end if;
 insert into public.kaiju_rolagens(usuario_id,kaiju_id,carta,ataque) values(auth.uid(),p_kaiju_id,escolha.carta,escolha.ataque);
 resultado:=jsonb_build_object('carta',escolha.carta,'ataque',escolha.ataque);
 insert into public.nave_operacoes values(auth.uid(),chave_op,resultado,now()); return resultado;
end $$;

create or replace function public.nave_sortear_aprimoramento(p_item text,p_operacao uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare f public.fichas_tripulantes; item jsonb; categorias text[]; categoria text; raridade text; sorteio double precision; efeito text; texto text; bonus numeric; qtd integer; resultado jsonb; gravado jsonb; chave_op text;
begin
 if auth.uid() is null or p_operacao is null then raise exception 'Entre na sua conta'; end if;
 chave_op:='aprimoramento:'||p_operacao;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||chave_op,0));
 select o.resultado into resultado from public.nave_operacoes o where usuario_id=auth.uid() and chave=chave_op;
 if found then return resultado; end if;
 select definicao into item from public.nave_itens_catalogo where id=p_item;
 if not found then raise exception 'Item não cadastrado'; end if;
 select * into f from public.fichas_tripulantes where id=auth.uid() for update;
 if not found then raise exception 'Ficha não encontrada'; end if;
 select array_agg(c) into categorias from unnest(array['cartas','atributo','adicional']) c where not coalesce((f.aprimoramentos_itens->p_item)?c,false);
 if coalesce(array_length(categorias,1),0)=0 then raise exception 'Item totalmente aprimorado'; end if;
 categoria:=categorias[1+floor(random()*array_length(categorias,1))::integer]; sorteio:=random();
 raridade:=case when sorteio<0.7 then 'comum' when sorteio<0.9 then 'incomum' else 'raro' end;
 if categoria='cartas' then
  qtd:=case raridade when 'comum' then 1 when 'incomum' then 2 else 3 end; texto:='Pode ser usado em +'||qtd||' carta(s) à escolha do jogador.';
 elsif categoria='atributo' then
  bonus:=case raridade when 'comum' then 20 when 'incomum' then 40 else 60 end; texto:='Dano do item aumentado em '||bonus||'%.';
  if coalesce((item->>'dano')::numeric,0)>0 then texto:=texto||' Dano base '||(item->>'dano')||' → '||round((item->>'dano')::numeric*(1+bonus/100),2)||'.'; end if;
 else
  if raridade='comum' then
   if random()<0.5 then efeito:='Ágil';texto:='Independente da agilidade do Kaiju, o jogador ataca antes.';else efeito:='Envenenamento';texto:='O dano extra causado no turno atual se mantém como dano adicional no turno seguinte.';end if;
  elsif raridade='incomum' then
   if random()<0.5 then efeito:='Fraqueza';texto:='Reduz em 50% o dano recebido pelo jogador nesta rodada.';else efeito:='Curandeiro';texto:='Recupera 15 de vida do jogador.';end if;
  else
   if random()<0.5 then efeito:='Cegueira';texto:='O ataque do Kaiju não acerta o jogador.';else efeito:='Lentidão';texto:='Passa a carta atual do Kaiju.';end if;
  end if;
  texto:=efeito||': '||texto;
  if raridade<>'comum' then texto:=texto||' Chance de ativação: '||round(100.0/greatest(1,jsonb_array_length(item->'cartas')),2)||'% por carta do item.';end if;
 end if;
 gravado:=public.combate_aprimorar(p_item,categoria,jsonb_build_object('raridade',raridade,'texto',texto,'efeito',efeito,'data',now()));
 resultado:=gravado||jsonb_build_object('categoria',categoria,'raridade',raridade,'texto',texto,'efeito',efeito);
 perform public.nave_registrar_evento('aprimoramentos',p_item,'sortear',categoria||' · '||raridade,jsonb_build_object('usuario_id',auth.uid(),'resultado',resultado-'aprimoramentos'));
 insert into public.nave_operacoes values(auth.uid(),chave_op,resultado,now()); return resultado;
end $$;

-- Leituras compartilhadas; imagens continuam em bucket privado e têm links temporários.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('kaijus-imagens','kaijus-imagens',false,4000000,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
drop policy if exists kaiju_imagens_leitura on storage.objects;
create policy kaiju_imagens_leitura on storage.objects for select to authenticated using(bucket_id='kaijus-imagens');
drop policy if exists kaiju_imagens_envio on storage.objects;
create policy kaiju_imagens_envio on storage.objects for insert to authenticated with check(bucket_id='kaijus-imagens' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists kaiju_imagens_remocao on storage.objects;
create policy kaiju_imagens_remocao on storage.objects for delete to authenticated using(bucket_id='kaijus-imagens' and (storage.foldername(name))[1]=auth.uid()::text and not exists(select 1 from public.mecha_kaijus_catalogo k where k.imagem_storage->>'path'=name));

-- Assinaturas explícitas mantêm as funções auxiliares fora do acesso do navegador.
revoke all on function public.nave_salvar_planeta(bigint,integer,jsonb),public.nave_salvar_item(bigint,integer,jsonb),public.nave_movimentar_item(bigint,integer,uuid),public.nave_arquivar_item(bigint,integer),public.nave_importar_legado(text,jsonb,jsonb),public.nave_salvar_kaiju(text,integer,jsonb),public.nave_sortear_ataque(text,uuid),public.nave_sortear_aprimoramento(text,uuid) from public,anon;
grant execute on function public.nave_salvar_planeta(bigint,integer,jsonb),public.nave_salvar_item(bigint,integer,jsonb),public.nave_movimentar_item(bigint,integer,uuid),public.nave_arquivar_item(bigint,integer),public.nave_importar_legado(text,jsonb,jsonb),public.nave_salvar_kaiju(text,integer,jsonb),public.nave_sortear_ataque(text,uuid),public.nave_sortear_aprimoramento(text,uuid) to authenticated;

-- Mudanças podem ser recebidas sem recarregar a página, quando Realtime está disponível.
do $$ declare t text; begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  foreach t in array array['nave_planetas','nave_inventario','nave_itens_catalogo','mecha_kaijus_catalogo'] loop
   if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
    execute format('alter publication supabase_realtime add table public.%I',t);
   end if;
  end loop;
 end if;
end $$;

-- Catálogos atuais: IDs preservados; registros já migrados não são sobrescritos.
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('manoplas-porco','Manoplas do Porco Kaiju',0,'{"id":"manoplas-porco","nome":"Manoplas do Porco Kaiju","origem":"Kaiju Porco","cartas":[1,2,9,10],"dano":5,"tipo":"Arma","descricao":"Combinação Esmagadora: para cada soco usado em sequência (turnos consecutivos), adicione +1 de dano acumulativo ao ataque."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('olho-porco','Olho do Porco Kaiju',1,'{"id":"olho-porco","nome":"Olho do Porco Kaiju","origem":"Kaiju Porco","cartas":["J"],"dano":0,"tipo":"Suporte","descricao":"Visão do Porco Caído: permite ver as próximas 3 cartas do topo do baralho e colocar uma no topo, garantindo o próximo saque."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('martelo-femur','Martelo Fêmur',2,'{"id":"martelo-femur","nome":"Martelo Fêmur","origem":"Kaiju Porco","cartas":[4,8],"dano":6,"danoSecundario":4,"tipo":"Arma AoE","descricao":"Onda de Choque (AoE): causa 6 de dano no alvo principal e 4 de dano nos demais inimigos da área."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('guincho-porco','Guincho do Porco',3,'{"id":"guincho-porco","nome":"Guincho do Porco","origem":"Kaiju Porco","cartas":["Q"],"dano":0,"tipo":"Condicional","descricao":"Com HP ≤ 50%, escolha uma carta de dano já usada no descarte e cause 2x o dano. Com HP > 50%, cura 4 de vida."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lingua-cobra','Língua de Cobra',4,'{"id":"lingua-cobra","nome":"Língua de Cobra","origem":"Serpente Falante","cartas":[4,8],"dano":4,"tipo":"Arma","descricao":"Memória Tática: acertar o nome do último ataque do chefe antes de rolar o dano eleva o ataque para 12."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('mascara-cobra','Máscara de Cobra',5,'{"id":"mascara-cobra","nome":"Máscara de Cobra","origem":"Serpente Falante","cartas":[6,7,8],"dano":0,"tipo":"Defensivo","descricao":"Contra-ataque: 50% de chance de esquivar de 100% do dano e refletir tudo de volta."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('laminas-gemeas','Lâminas Gêmeas',6,'{"id":"laminas-gemeas","nome":"Lâminas Gêmeas","origem":"Serpente Falante","cartas":[1,2,3,4],"dano":9,"danoParcial":5,"tipo":"Arma","descricao":"Equipar apenas 2 cartas causa 5 de dano. Dedicar as cartas 1, 2, 3 e 4 causa 9 de dano por acerto."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-vorpal','Lâmina Vorpal',7,'{"id":"lamina-vorpal","nome":"Lâmina Vorpal","origem":"Serpente Falante","cartas":[1,3,9,10],"dano":5,"tipo":"Arma","descricao":"Se a Velocidade do Mecha for maior que a do inimigo, o dano triplica para 15. Enquanto equipada, recebe -2 de Defesa Fixa."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('coracao-verdejante','Coração Verdejante',8,'{"id":"coracao-verdejante","nome":"Coração Verdejante","origem":"Kaiju Rei Verdejante","cartas":["Q"],"dano":0,"tipo":"Artefato","descricao":"Sobrecarga: sacrifica 4 HP do Mecha e concede +10 de dano ao próximo ataque com qualquer arma."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-verdejante','Lâmina Verdejante',9,'{"id":"lamina-verdejante","nome":"Lâmina Verdejante","origem":"Kaiju Rei Verdejante","cartas":[4,5,6],"dano":5,"tipo":"Arma","descricao":"Condicional: se a carta do inimigo neste turno for ímpar, a lâmina causa 8 de dano no total."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('canhao-verdejante','Canhão Verdejante',10,'{"id":"canhao-verdejante","nome":"Canhão Verdejante","origem":"Kaiju Rei Verdejante","cartas":[2,8],"dano":15,"tipo":"Arma","descricao":"Recarga: começa carregado. Depois do disparo, tirar 2 ou 8 causa 0 de dano naquele acionamento e recarrega a arma."}'::jsonb) on conflict(id) do nothing;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('vigilancia-verdejante','Vigilância Verdejante',11,'{"id":"vigilancia-verdejante","nome":"Vigilância Verdejante","origem":"Kaiju Rei Verdejante","cartas":["K"],"dano":0,"tipo":"Drone","descricao":"Invocação (15 HP): cria um drone. Enquanto ativo, ataques bem-sucedidos recebem +4 de dano, e o drone absorve dano antes do Mecha."}'::jsonb) on conflict(id) do nothing;
update public.mecha_kaijus_catalogo set vida=case when vida>0 then vida else 220 end,agilidade=case when agilidade>0 then agilidade else 6 end,defesa=case when defesa<>0 then defesa else 0 end,codex_texto='Ao acertar o nome e o efeito de todas as habilidades deste Kaiju, você recebe um ataque dele de Ás a 10.',ataques='{"2":{"nome":"Foco no vigor","dano":6,"descricao":"6 de dano no jogador com mais vida."},"3":{"nome":"Teste de juventude","dano":6,"descricao":"6 de dano no jogador mais novo."},"4":{"nome":"Teste de juventude","dano":7,"descricao":"7 de dano no jogador mais novo."},"5":{"nome":"Respeito aos anciões","dano":6,"descricao":"6 de dano no jogador mais velho."},"6":{"nome":"Respeito aos anciões","dano":7,"descricao":"7 de dano no jogador mais velho."},"7":{"nome":"Predador cruel","dano":5,"descricao":"Acerta o jogador com menos vida."},"8":{"nome":"Predador cruel","dano":5,"descricao":"Acerta o jogador com menos vida."},"9":{"nome":"Explosão de pólen","dano":2,"descricao":"Causa 2 de dano em todos os jogadores."},"10":{"nome":"Terremoto da selva","dano":3,"descricao":"Causa 3 de dano em todos os jogadores."},"A":{"nome":"Foco no vigor","dano":7,"descricao":"7 de dano no jogador com mais vida."},"J":{"nome":"Elo da natureza","dano":0,"descricao":"Todos os jogadores ficam de mãos dadas."},"Q":{"nome":"Mil olhos da floresta","dano":0,"descricao":"Descarta duas cartas do baralho."},"K":{"nome":"A horda do chefe","dano":3,"descricao":"Invoca 2 Kaijus; o grupo escolhe um jogador para tomar 3 de dano toda rodada."}}'::jsonb where id='rei-verdejante' and ataques='{}'::jsonb and not personalizado;
update public.mecha_kaijus_catalogo set vida=case when vida>0 then vida else 110 end,agilidade=case when agilidade>0 then agilidade else 5 end,defesa=case when defesa<>0 then defesa else 0 end,codex_texto='Ao acertar o nome e o efeito de todas as habilidades deste Kaiju, você recebe um ataque dele de Ás a 10.',ataques='{"2":{"nome":"Coice pela direita","dano":4,"descricao":"O Kaiju avança e acerta o jogador mais à esquerda da mesa."},"3":{"nome":"Mordida frontal","dano":4,"descricao":"Acerta o jogador do meio."},"4":{"nome":"Mordida frontal","dano":4,"descricao":"Acerta o jogador do meio."},"5":{"nome":"Coice pela direita","dano":5,"descricao":"Acerta o jogador da direita da mesa."},"6":{"nome":"Coice pela direita","dano":6,"descricao":"Acerta o jogador da direita da mesa."},"7":{"nome":"Fúria às cegas","dano":6,"descricao":"Atinge um alvo aleatório."},"8":{"nome":"Guincho aterrorizante","dano":4,"descricao":"Escolha qual jogador vai receber 4 de dano."},"9":{"nome":"Fúria suína","dano":60,"descricao":"Todos os oponentes perdem 3 de vida."},"10":{"nome":"Atropelamento desconcertado","dano":3,"descricao":"Corre e acerta dois alvos aleatórios."},"A":{"nome":"Mordida frontal","dano":4,"descricao":"Acerta o jogador do meio."},"J":{"nome":"Porco cego e mudo","dano":4,"descricao":"O grupo fecha os olhos e aponta para quem toma 4 de dano. Se todos discordarem, o grupo todo toma 4."},"Q":{"nome":"Cuspindo ácido","dano":5,"descricao":"Dá 5 de dano e descarta duas cartas do baralho."},"K":{"nome":"Rei: nhoc e porco","dano":4,"descricao":"Ao falar “nhoc”, passa para outra pessoa; “porco” inverte a ordem. Quem falar errado ou fora da vez toma 4."}}'::jsonb where id='rei-porco' and ataques='{}'::jsonb and not personalizado;
update public.mecha_kaijus_catalogo set vida=case when vida>0 then vida else 180 end,agilidade=case when agilidade>0 then agilidade else 7 end,defesa=case when defesa<>0 then defesa else 0 end,codex_texto='Ao acertar o nome e o efeito de todas as habilidades deste Kaiju, você recebe um ataque dele de Ás a 10.',ataques='{"2":{"nome":"Sufocamento","dano":7,"descricao":"Atinge o jogador à esquerda."},"3":{"nome":"Presa caótica","dano":7,"descricao":"Atinge um alvo aleatório."},"4":{"nome":"Bate nas extremidades","dano":5,"descricao":"Bate nas extremidades."},"5":{"nome":"Giro rasteiro","dano":3,"descricao":"Quem sofre o dano troca de lugar."},"6":{"nome":"Cuspida tóxica","dano":5,"descricao":"Acerta o jogador mais ao meio."},"7":{"nome":"Espreita ilusória","dano":7,"descricao":"Acerta um alvo aleatório."},"8":{"nome":"Bote surpresa","dano":5,"descricao":"Ataca o jogador do meio."},"9":{"nome":"Bote cego","dano":5,"descricao":"Acerta um jogador aleatório."},"10":{"nome":"Cauda chicote tempestuoso","dano":3,"descricao":"Causa 3 de dano em todos os jogadores."},"A":{"nome":"Bote preciso","dano":7,"descricao":"Atinge o jogador à direita."},"J":{"nome":"Jogo da memória","dano":5,"descricao":"Memorize: Escama, veneno, bote, asas, chocalho, sombras. Se errar, recebe 5 de dano."},"Q":{"nome":"Abrir asas","dano":5,"descricao":"Todo golpe tem 50% de chance de erro."},"K":{"nome":"Serpente enfeitiçou","dano":7,"descricao":"Enfeitiça o jogador e causa 7 de dano."}}'::jsonb where id='cobra-falante' and ataques='{}'::jsonb and not personalizado;
update public.mecha_kaijus_catalogo set vida=case when vida>0 then vida else 400 end,agilidade=case when agilidade>0 then agilidade else 7 end,defesa=case when defesa<>0 then defesa else 0 end,codex_texto='Uma criatura de múltiplas cabeças capaz de atacar seus inimigos de diferentes formas. Seus ataques podem atingir vários jogadores e causar efeitos de caos.',ataques='{"2":{"nome":"Foco do predador Alfa","dano":14,"descricao":"Causa 14 de dano no último jogador que recebeu dano."},"3":{"nome":"Bote impiedoso","dano":13,"descricao":"Causa 13 de dano no jogador da ponta com mais vida."},"4":{"nome":"Investida caótica","dano":12,"descricao":"Causa 12 de dano em um jogador aleatório."},"5":{"nome":"Miasma do Caos","dano":6,"descricao":"Causa 6 de dano em todos os jogadores."},"6":{"nome":"Ressonância do Caos","dano":0,"descricao":"Repete a última carta da rodada."},"7":{"nome":"Prisão de escamas","dano":7,"descricao":"Causa 7 de dano no centro; os dois jogadores do meio não podem causar dano neste turno."},"8":{"nome":"Rugido paralisante","dano":9,"descricao":"Causa 9 de dano e bloqueia o dano de 2 jogadores."},"9":{"nome":"Mutação regenerativa","dano":0,"descricao":"Recupera 20 de vida com a cabeça que estiver com menos vida."},"10":{"nome":"Apocalipse Kaiju","dano":"4X de -4","descricao":"Bate 4 vezes, causando 4 de dano em cada golpe."},"A":{"nome":"Mordida corrosiva","dano":10,"descricao":"Causa 10 de dano em um jogador e 5 de dano no restante."},"J":{"nome":"Maldição das vozes","dano":0,"descricao":"Cada jogador só pode falar 1 palavra até todos terem falado. Quem errar perde 4 de vida."},"Q":{"nome":"Enigma do caos","dano":6,"descricao":"Os jogadores devem repetir o trava-língua apresentado. Quem errar perde 6 de vida."},"K":{"nome":"Dança da hidra","dano":0,"descricao":"Um jogador é escolhido como a mente da Hidra; tudo que ele fizer deve ser repetido pelos demais por 3 turnos."}}'::jsonb where id='hidra' and ataques='{}'::jsonb and not personalizado;
update public.mecha_kaijus_catalogo set vida=case when vida>0 then vida else 340 end,agilidade=case when agilidade>0 then agilidade else 6 end,defesa=case when defesa<>0 then defesa else 2 end,codex_texto='Uma criatura colossal que combina a resistência de uma tartaruga com o poder destrutivo de um dragão.',ataques='{"2":{"nome":"Casco esmagador","dano":12,"descricao":"Causa 12 de dano no jogador com mais vida."},"3":{"nome":"Tremor de terra","dano":1,"descricao":"Causa 1 de dano em todos os jogadores."},"4":{"nome":"Punição do casco","dano":4,"descricao":"Causa 4 de dano; a equipe escolhe quem recebe."},"5":{"nome":"Mordida quebra-ossos","dano":4,"descricao":"Causa 4 de dano; se o alvo atacou o Kaiju, causa 8."},"6":{"nome":"Âncora de dano","dano":7,"descricao":"Causa 7 de dano; a equipe escolhe quem recebe."},"7":{"nome":"Repulsa brutal","dano":5,"descricao":"Causa 5 de dano; a equipe escolhe quem recebe."},"8":{"nome":"Muralha de espinhos","dano":5,"descricao":"Devolve 3 de dano."},"9":{"nome":"Gêiser subterrâneo","dano":6,"descricao":"Causa 6 de dano em um jogador aleatório."},"10":{"nome":"Peso do milênio","dano":1,"descricao":"O dano é dobrado."},"A":{"nome":"Esmagar defesa","dano":9,"descricao":"Causa 9 de dano no alvo escolhido pela equipe."},"J":{"nome":"Instância mutável","dano":2,"descricao":"2 de dano e 5 de defesa, ou 2 de dano e -2."},"Q":{"nome":"Distorção temporal","dano":0,"descricao":"Um jogador fica em estátua, inquieto, agitado e lento. O efeito acaba quando o Kaiju sofre 80 de dano."},"K":{"nome":"Palácio do equilíbrio","dano":4,"descricao":"Se a torre de cartas cair, o Kaiju fica imune, recebe 20 cartas e toma 4 de dano."}}'::jsonb where id='tartaruga-dragao' and ataques='{}'::jsonb and not personalizado;

commit;
