-- NAVE 3B V8 — catálogo completo de itens + seleção persistente dos Codex
-- Execute este arquivo no SQL Editor do Supabase depois das atualizações V6/V7.

alter table public.fichas_tripulantes add column if not exists codex_selecoes jsonb not null default '{}'::jsonb;
grant update (codex_selecoes) on public.fichas_tripulantes to authenticated;

insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('manoplas-porco','Manoplas do Porco Kaiju',0,'{"id":"manoplas-porco","nome":"Manoplas do Porco Kaiju","origem":"Kaiju Porco","cartas":[1,2,9,10],"dano":5,"tipo":"Arma","descricao":"Combinação Esmagadora: para cada soco usado em sequência (turnos consecutivos), adicione +1 de dano acumulativo ao ataque."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('olho-porco','Olho do Porco Kaiju',1,'{"id":"olho-porco","nome":"Olho do Porco Kaiju","origem":"Kaiju Porco","cartas":["J"],"dano":0,"tipo":"Suporte","descricao":"Visão do Porco Caído: permite ver as próximas 3 cartas do topo do baralho e colocar uma no topo, garantindo o próximo saque."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('martelo-femur','Martelo Fêmur',2,'{"id":"martelo-femur","nome":"Martelo Fêmur","origem":"Kaiju Porco","cartas":[4,8],"dano":6,"danoSecundario":4,"tipo":"Arma AoE","descricao":"Onda de Choque (AoE): causa 6 de dano no alvo principal e 4 de dano nos demais inimigos da área."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('guincho-porco','Guincho do Porco',3,'{"id":"guincho-porco","nome":"Guincho do Porco","origem":"Kaiju Porco","cartas":["Q"],"dano":0,"tipo":"Condicional","descricao":"Com HP ≤ 50% (Desespero), escolha uma carta de dano já usada no descarte e cause 2x o dano. Com HP > 50% (Estável), cura 4 de vida."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('codex-porco','Codex Kaiju Porco',4,'{"id":"codex-porco","nome":"Codex Kaiju Porco","origem":"Kaiju Porco","cartas":[],"dano":0,"tipo":"Codex","codexKaijuId":"rei-porco","descricao":"Escolha um ataque de Ás a 10 do Codex do Kaiju Porco. O ataque escolhido passa a ser o efeito deste item."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lingua-cobra','Língua de Cobra',5,'{"id":"lingua-cobra","nome":"Língua de Cobra","origem":"Serpente Falante","cartas":[4,8],"dano":4,"tipo":"Arma","descricao":"Memória Tática: acertar o nome do último ataque do chefe antes de rolar o dano eleva o ataque para 12."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('mascara-cobra','Máscara de Cobra',6,'{"id":"mascara-cobra","nome":"Máscara de Cobra","origem":"Serpente Falante","cartas":[6,7,8],"dano":0,"tipo":"Defensivo","descricao":"Contra-ataque: 50% de chance de esquivar de 100% do dano e refletir tudo de volta."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('laminas-gemeas','Lâminas Gêmeas',7,'{"id":"laminas-gemeas","nome":"Lâminas Gêmeas","origem":"Serpente Falante","cartas":[1,2,3,4],"dano":9,"danoParcial":5,"tipo":"Arma","descricao":"Equipar apenas 2 cartas causa 5 de dano. Dedicar as cartas 1, 2, 3 e 4 causa 9 de dano por acerto."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-vorpal','Lâmina Vorpal',8,'{"id":"lamina-vorpal","nome":"Lâmina Vorpal","origem":"Serpente Falante","cartas":[1,3,9,10],"dano":5,"tipo":"Arma Especial","descricao":"Se a Velocidade do Mecha for maior que a do inimigo, o dano triplica para 15. Enquanto equipada, recebe -2 de Defesa Fixa."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('codex-serpente','Codex Serpente Falante',9,'{"id":"codex-serpente","nome":"Codex Serpente Falante","origem":"Serpente Falante","cartas":[],"dano":0,"tipo":"Codex","codexKaijuId":"cobra-falante","descricao":"Escolha um ataque de Ás a 10 do Codex da Serpente Falante. O ataque escolhido passa a ser o efeito deste item."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('coracao-verdejante','Coração Verdejante',10,'{"id":"coracao-verdejante","nome":"Coração Verdejante","origem":"Rei Verdejante","cartas":["Q"],"dano":0,"tipo":"Artefato","descricao":"Sobrecarga: sacrifica 4 HP do Mecha e concede +10 de dano ao próximo ataque com qualquer arma."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-verdejante','Lâmina Verdejante',11,'{"id":"lamina-verdejante","nome":"Lâmina Verdejante","origem":"Rei Verdejante","cartas":[4,5,6],"dano":5,"tipo":"Arma","descricao":"Condicional: se a carta do inimigo neste turno for ímpar, a lâmina causa 8 de dano no total."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('canhao-verdejante','Canhão Verdejante',12,'{"id":"canhao-verdejante","nome":"Canhão Verdejante","origem":"Rei Verdejante","cartas":[2,8],"dano":15,"tipo":"Arma","descricao":"Recarga: começa carregado. Depois do disparo, tirar 2 ou 8 causa 0 de dano naquele acionamento e recarrega a arma."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('vigilancia-verdejante','Vigilância Verdejante',13,'{"id":"vigilancia-verdejante","nome":"Vigilância Verdejante","origem":"Rei Verdejante","cartas":["K"],"dano":0,"tipo":"Drone","descricao":"Invocação (15 HP): cria um drone. Enquanto ativo, ataques bem-sucedidos recebem +4 de dano, e o drone absorve dano antes do Mecha."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('codex-verdejante','Codex Rei Verdejante',14,'{"id":"codex-verdejante","nome":"Codex Rei Verdejante","origem":"Rei Verdejante","cartas":[],"dano":0,"tipo":"Codex","codexKaijuId":"rei-verdejante","descricao":"Escolha um ataque de Ás a 10 do Codex do Rei Verdejante. O ataque escolhido passa a ser o efeito deste item."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lanca-caotica-bifurcada','Lança Caótica Bifurcada',15,'{"id":"lanca-caotica-bifurcada","nome":"Lança Caótica Bifurcada","origem":"Hidra Caótica","cartas":[4,5,6],"dano":20,"tipo":"Arma","descricao":"Dano Dividido: alternativamente, causa 15 de dano a até dois alvos simultâneos."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('chicote-caotico-hidra','Chicote Caótico da Hidra',16,'{"id":"chicote-caotico-hidra","nome":"Chicote Caótico da Hidra","origem":"Hidra Caótica","cartas":[4,6,8],"dano":11,"tipo":"Arma","descricao":"Se a sua Velocidade for maior que a do inimigo, causa 15 de dano + seu valor atual de Velocidade como dano bônus extra."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('canhao-caotico-acumulado','Canhão Caótico Acumulado',17,'{"id":"canhao-caotico-acumulado","nome":"Canhão Caótico Acumulado","origem":"Hidra Caótica","cartas":[5,"J","Q","K"],"dano":0,"tipo":"Arma Condicional","descricao":"Ao ativar no 5, não ataca: anula e armazena 100% do dano sofrido no turno. Ao sacar J, Q ou K, dispara automaticamente e causa o dano armazenado ×1,5."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-caotica','Lâmina Caótica',18,'{"id":"lamina-caotica","nome":"Lâmina Caótica","origem":"Hidra Caótica","cartas":["J"],"dano":1,"tipo":"Arma","danoDinamico":true,"descricao":"Cada golpe causa 1 de dano base + seu Dano Extra. O número de golpes é igual ao valor atual de Agilidade."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('genoma-hidra','Genoma da Hidra',19,'{"id":"genoma-hidra","nome":"Genoma da Hidra","origem":"Hidra Caótica","cartas":["K"],"dano":0,"tipo":"Artefato","descricao":"Sua vida atual vira a vida máxima e o Mecha se divide em dois, cada um com 50% dessa vida. O original mantém bônus e a cópia replica seus ataques."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('codex-hidra','Codex Hidra Caótica',20,'{"id":"codex-hidra","nome":"Codex Hidra Caótica","origem":"Hidra Caótica","cartas":[],"dano":0,"tipo":"Codex","codexKaijuId":"hidra","descricao":"Escolha um ataque de Ás a 10 do Codex da Hidra Caótica. O ataque escolhido passa a ser o efeito deste item."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('escudo-farpado','Escudo Farpado',21,'{"id":"escudo-farpado","nome":"Escudo Farpado","origem":"Tartaruga Dragão","cartas":[1,8,9],"dano":0,"tipo":"Defensivo","danoDinamico":true,"descricao":"Retaliação: causa dano ofensivo igual à sua Defesa total ×3. Defesa Ativa: adiciona +2 de Defesa neste turno."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('martelo-dragao','Martelo Dragão',22,'{"id":"martelo-dragao","nome":"Martelo Dragão","origem":"Tartaruga Dragão","cartas":[3,7,10],"dano":10,"tipo":"Arma","descricao":"Carga Esmagadora: pode carregar por um turno para causar 30 de dano. Se sofrer dano durante a carga, o ataque é cancelado."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('furia-dragao','Fúria do Dragão',23,'{"id":"furia-dragao","nome":"Fúria do Dragão","origem":"Tartaruga Dragão","cartas":["J"],"dano":0,"tipo":"Artefato","descricao":"Poder Irrestrito: aumenta o dano base do jogador em +2. Preço de Sangue: ao ativar, o Mecha perde 1 ponto de Defesa."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('lamina-cega','Lâmina Cega',24,'{"id":"lamina-cega","nome":"Lâmina Cega","origem":"Tartaruga Dragão","cartas":["Q"],"dano":0,"tipo":"Arma Condicional","danoDinamico":true,"descricao":"Impacto: causa dano igual à metade da sua vida atual, arredondado. Golpe Desesperado: usa sua própria integridade como arma."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('tambor-tartaruga-dragao','Tambor da Tartaruga Dragão',25,'{"id":"tambor-tartaruga-dragao","nome":"Tambor da Tartaruga Dragão","origem":"Tartaruga Dragão","cartas":["K"],"dano":0,"tipo":"Suporte","descricao":"Ritmo de Batalha: você não ataca, mas aliados causam +50% de dano enquanto a dança permanecer. A dança termina ao sofrer 20 ou mais de dano; a cada turno, empilhe duas cartas em uma torre com base máxima de 2."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;
insert into public.nave_itens_catalogo(id,nome,ordem,definicao) values('codex-tartaruga-dragao','Codex Tartaruga Dragão',26,'{"id":"codex-tartaruga-dragao","nome":"Codex Tartaruga Dragão","origem":"Tartaruga Dragão","cartas":[],"dano":0,"tipo":"Codex","codexKaijuId":"tartaruga-dragao","descricao":"Escolha um ataque de Ás a 10 do Codex da Tartaruga Dragão. O ataque escolhido passa a ser o efeito deste item."}'::jsonb) on conflict(id) do update set nome=excluded.nome,ordem=excluded.ordem,definicao=excluded.definicao;

-- A oficina usa a carta escolhida do Codex para dano e quantidade de cartas.
create or replace function public.nave_sortear_aprimoramento(p_item text,p_operacao uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare f public.fichas_tripulantes; item jsonb; categorias text[]; categoria text; raridade text; sorteio double precision; efeito text; texto text; bonus numeric; qtd integer; resultado jsonb; gravado jsonb; chave_op text; codex_id text; codex_carta text; codex_ataque jsonb;
begin
 if auth.uid() is null or p_operacao is null then raise exception 'Entre na sua conta'; end if;
 chave_op:='aprimoramento:'||p_operacao;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||chave_op,0));
 select o.resultado into resultado from public.nave_operacoes o where usuario_id=auth.uid() and chave=chave_op;
 if found then return resultado; end if;
 select definicao into item from public.nave_itens_catalogo where id=p_item;
 if not found then raise exception 'Item não cadastrado'; end if;
 select * into f from public.fichas_tripulantes where id=auth.uid() for update;
 if not found then raise exception 'Ficha não encontrada'; end if;
 if not coalesce(f.itens_catalogo ? p_item,false) then raise exception 'Salve este item na sua ficha primeiro'; end if;
 codex_id:=nullif(item->>'codexKaijuId','');
 if codex_id is not null then
   codex_carta:=nullif(f.codex_selecoes->>p_item,'');
   if codex_carta is null or codex_carta not in ('A','2','3','4','5','6','7','8','9','10') then raise exception 'Selecione um ataque de A a 10 para este Codex na Ficha do Tripulante'; end if;
   select ataques->codex_carta into codex_ataque from public.mecha_kaijus_catalogo where id=codex_id;
   if codex_ataque is null then raise exception 'Ataque do Codex não encontrado no Registro de Kaijus'; end if;
   item:=item||jsonb_build_object('cartas',jsonb_build_array(codex_carta),'dano',coalesce(codex_ataque->'dano','0'::jsonb),'descricao',coalesce(codex_ataque->>'descricao',''));
 end if;
 select array_agg(c) into categorias from unnest(array['cartas','atributo','adicional']) c where not coalesce((f.aprimoramentos_itens->p_item)?c,false);
 if coalesce(array_length(categorias,1),0)=0 then raise exception 'Item totalmente aprimorado'; end if;
 categoria:=categorias[1+floor(random()*array_length(categorias,1))::integer]; sorteio:=random();
 raridade:=case when sorteio<0.7 then 'comum' when sorteio<0.9 then 'incomum' else 'raro' end;
 if categoria='cartas' then
  qtd:=case raridade when 'comum' then 1 when 'incomum' then 2 else 3 end; texto:='Pode ser usado em +'||qtd||' carta(s) à escolha do jogador.';
 elsif categoria='atributo' then
  bonus:=case raridade when 'comum' then 20 when 'incomum' then 40 else 60 end; texto:='Dano do item aumentado em '||bonus||'%.';
  if jsonb_typeof(item->'dano')='number' and coalesce((item->>'dano')::numeric,0)>0 then texto:=texto||' Dano base '||(item->>'dano')||' → '||round((item->>'dano')::numeric*(1+bonus/100),2)||'.'; end if;
 else
  if raridade='comum' then
   if random()<0.5 then efeito:='Ágil';texto:='Independente da agilidade do Kaiju, o jogador ataca antes.';else efeito:='Envenenamento';texto:='O dano extra causado no turno atual se mantém como dano adicional no turno seguinte.';end if;
  elsif raridade='incomum' then
   if random()<0.5 then efeito:='Fraqueza';texto:='Reduz em 50% o dano recebido pelo jogador nesta rodada.';else efeito:='Curandeiro';texto:='Recupera 15 de vida do jogador.';end if;
  else
   if random()<0.5 then efeito:='Cegueira';texto:='O ataque do Kaiju não acerta o jogador.';else efeito:='Lentidão';texto:='Passa a carta atual do Kaiju.';end if;
  end if;
  texto:=efeito||': '||texto;
  if raridade<>'comum' then texto:=texto||' Chance de ativação: '||round(100.0/greatest(1,jsonb_array_length(coalesce(item->'cartas','[]'::jsonb))),2)||'% por carta do item.';end if;
 end if;
 gravado:=public.combate_aprimorar(p_item,categoria,jsonb_build_object('raridade',raridade,'texto',texto,'efeito',efeito,'data',now(),'codex_carta',codex_carta));
 resultado:=gravado||jsonb_build_object('categoria',categoria,'raridade',raridade,'texto',texto,'efeito',efeito,'codex_carta',codex_carta);
 perform public.nave_registrar_evento('aprimoramentos',p_item,'sortear',categoria||' · '||raridade,jsonb_build_object('usuario_id',auth.uid(),'resultado',resultado-'aprimoramentos'));
 insert into public.nave_operacoes values(auth.uid(),chave_op,resultado,now()); return resultado;
end $$;
revoke all on function public.nave_sortear_aprimoramento(text,uuid) from public, anon;
grant execute on function public.nave_sortear_aprimoramento(text,uuid) to authenticated;

select 'V8 aplicada: itens atualizados e Codex habilitados.' as resultado;
