-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Ele cria o estado global da integridade, o histórico e a operação atômica
-- que impede duas recuperações simultâneas.

create table if not exists public.nave_integridade (
    id smallint primary key default 1 check (id = 1),
    valor integer not null default 5,
    maximo integer not null default 15 check (maximo > 0),
    ultima_recuperacao timestamptz,
    ultimo_usuario_id uuid references auth.users(id) on delete set null,
    ultimo_usuario_nome text,
    atualizado_em timestamptz not null default now(),
    constraint nave_integridade_valor_valido check (
        valor >= 0 and valor <= maximo
    )
);

insert into public.nave_integridade (id, valor, maximo)
values (1, 5, 15)
on conflict (id) do nothing;

create table if not exists public.nave_integridade_historico (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users(id) on delete set null,
    usuario_nome text not null,
    valor_anterior integer not null,
    valor_novo integer not null,
    recuperado_em timestamptz not null default now()
);

alter table public.nave_integridade enable row level security;
alter table public.nave_integridade_historico enable row level security;

revoke insert, update, delete on public.nave_integridade from authenticated;
revoke insert, update, delete on public.nave_integridade_historico from authenticated;
grant select on public.nave_integridade to authenticated;
grant select on public.nave_integridade_historico to authenticated;

drop policy if exists "Tripulantes podem ver a integridade" on public.nave_integridade;
create policy "Tripulantes podem ver a integridade"
on public.nave_integridade
for select
to authenticated
using (true);

drop policy if exists "Tripulantes podem ver o histórico" on public.nave_integridade_historico;
create policy "Tripulantes podem ver o histórico"
on public.nave_integridade_historico
for select
to authenticated
using (true);

create or replace function public.recuperar_integridade_nave()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_usuario_id uuid := auth.uid();
    v_usuario_nome text;
    v_estado public.nave_integridade%rowtype;
    v_agora timestamptz := clock_timestamp();
begin
    if v_usuario_id is null then
        raise exception 'Usuário não autenticado';
    end if;

    select coalesce(
        nullif(trim(nome), ''),
        nullif(trim(username), ''),
        'Tripulante'
    )
    into v_usuario_nome
    from public.profiles
    where id = v_usuario_id;

    v_usuario_nome := coalesce(v_usuario_nome, 'Tripulante');

    select *
    into v_estado
    from public.nave_integridade
    where id = 1
    for update;

    if not found then
        raise exception 'Estado de integridade não encontrado';
    end if;

    if v_estado.valor >= v_estado.maximo then
        return jsonb_build_object(
            'sucesso', false,
            'codigo', 'integridade_maxima',
            'valor', v_estado.valor,
            'maximo', v_estado.maximo,
            'ultima_recuperacao', v_estado.ultima_recuperacao,
            'ultimo_usuario_nome', v_estado.ultimo_usuario_nome
        );
    end if;

    if v_estado.ultima_recuperacao is not null
       and v_estado.ultima_recuperacao > v_agora - interval '20 hours' then
        return jsonb_build_object(
            'sucesso', false,
            'codigo', 'tempo_bloqueado',
            'valor', v_estado.valor,
            'maximo', v_estado.maximo,
            'ultima_recuperacao', v_estado.ultima_recuperacao,
            'ultimo_usuario_nome', v_estado.ultimo_usuario_nome
        );
    end if;

    update public.nave_integridade
    set valor = valor + 1,
        ultima_recuperacao = v_agora,
        ultimo_usuario_id = v_usuario_id,
        ultimo_usuario_nome = v_usuario_nome,
        atualizado_em = v_agora
    where id = 1
    returning * into v_estado;

    insert into public.nave_integridade_historico (
        usuario_id,
        usuario_nome,
        valor_anterior,
        valor_novo,
        recuperado_em
    ) values (
        v_usuario_id,
        v_usuario_nome,
        v_estado.valor - 1,
        v_estado.valor,
        v_agora
    );

    return jsonb_build_object(
        'sucesso', true,
        'codigo', 'recuperado',
        'valor', v_estado.valor,
        'maximo', v_estado.maximo,
        'ultima_recuperacao', v_estado.ultima_recuperacao,
        'ultimo_usuario_nome', v_estado.ultimo_usuario_nome
    );
end;
$$;

revoke all on function public.recuperar_integridade_nave() from public;
grant execute on function public.recuperar_integridade_nave() to authenticated;

-- Ativa a atualização instantânea nos navegadores conectados.
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nave_integridade'
    ) then
        alter publication supabase_realtime
        add table public.nave_integridade;
    end if;
end;
$$;
