-- ============================================================
-- NAVE 3B — CENTRAL AUTOMATIZADA DE COMBATE
-- Execute este arquivo inteiro no SQL Editor do Supabase.
-- Seguro para executar novamente: tabelas e funções são atualizadas.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. BATALHAS
-- O campo estado guarda um snapshot completo das duas lutas.
-- A imagem fica fora do JSON para não ser repetida em toda rodada.
-- ------------------------------------------------------------

create table if not exists public.arena_batalhas (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    boss_nome text not null,
    boss_imagem text,
    boss_regras_texto text not null default '',
    status text not null default 'em_andamento'
        check (status in ('em_andamento', 'pausada', 'finalizada')),
    rodada_atual integer not null default 1 check (rodada_atual >= 1),
    estado jsonb not null default '{}'::jsonb,
    criado_por uuid not null default auth.uid() references auth.users(id) on delete restrict,
    criado_por_nome text not null default 'Tripulante',
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now()
);

create index if not exists arena_batalhas_atualizado_idx
    on public.arena_batalhas (atualizado_em desc);

create index if not exists arena_batalhas_status_idx
    on public.arena_batalhas (status, atualizado_em desc);

-- ------------------------------------------------------------
-- 2. RODADAS
-- Cada registro contém cartas, memória anterior e resultado final.
-- Isso permite auditoria e desfazer sem perder a consistência.
-- ------------------------------------------------------------

create table if not exists public.arena_rodadas (
    id bigint generated by default as identity primary key,
    batalha_id uuid not null references public.arena_batalhas(id) on delete cascade,
    numero integer not null check (numero >= 1),
    carta_boss text not null,
    carta_frota_1 text not null,
    carta_frota_2 text not null,
    resumo jsonb not null default '{}'::jsonb,
    estado_antes jsonb not null,
    estado_depois jsonb not null,
    registrado_por uuid not null default auth.uid() references auth.users(id) on delete restrict,
    registrado_por_nome text not null default 'Tripulante',
    registrado_em timestamptz not null default now(),
    unique (batalha_id, numero)
);

create index if not exists arena_rodadas_batalha_idx
    on public.arena_rodadas (batalha_id, numero desc);

-- ------------------------------------------------------------
-- 3. NOMES E DATAS AUTOMÁTICOS
-- ------------------------------------------------------------

create or replace function public.arena_nome_usuario(p_usuario_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        nullif(trim(p.nome), ''),
        nullif(trim(p.username), ''),
        'Tripulante'
    )
    from public.profiles p
    where p.id = p_usuario_id
    limit 1;
$$;

create or replace function public.arena_preparar_batalha()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op = 'INSERT' then
        new.criado_por := coalesce(new.criado_por, auth.uid());
        new.criado_por_nome := coalesce(
            public.arena_nome_usuario(new.criado_por),
            'Tripulante'
        );
        new.criado_em := coalesce(new.criado_em, now());
    else
        new.criado_por := old.criado_por;
        new.criado_por_nome := old.criado_por_nome;
        new.criado_em := old.criado_em;
    end if;

    new.atualizado_em := now();
    return new;
end;
$$;

drop trigger if exists arena_batalhas_preparar on public.arena_batalhas;
create trigger arena_batalhas_preparar
before insert or update on public.arena_batalhas
for each row execute function public.arena_preparar_batalha();

-- ------------------------------------------------------------
-- 4. RLS
-- Todos os usuários autenticados da Nave podem acompanhar e operar
-- batalhas. Visitantes sem login não recebem acesso.
-- ------------------------------------------------------------

alter table public.arena_batalhas enable row level security;
alter table public.arena_rodadas enable row level security;

drop policy if exists "arena_batalhas_ler_autenticado" on public.arena_batalhas;
create policy "arena_batalhas_ler_autenticado"
on public.arena_batalhas for select
to authenticated
using (true);

drop policy if exists "arena_batalhas_criar_autenticado" on public.arena_batalhas;
create policy "arena_batalhas_criar_autenticado"
on public.arena_batalhas for insert
to authenticated
with check (auth.uid() = criado_por);

drop policy if exists "arena_batalhas_atualizar_autenticado" on public.arena_batalhas;
create policy "arena_batalhas_atualizar_autenticado"
on public.arena_batalhas for update
to authenticated
using (true)
with check (true);

drop policy if exists "arena_rodadas_ler_autenticado" on public.arena_rodadas;
create policy "arena_rodadas_ler_autenticado"
on public.arena_rodadas for select
to authenticated
using (true);

-- Inserções e exclusões de rodadas acontecem somente pelas funções
-- transacionais abaixo. Isso impede clique duplicado e rodada repetida.

-- ------------------------------------------------------------
-- 5. RESOLVER UMA RODADA ATOMICAMENTE
-- A linha da batalha é bloqueada enquanto a rodada é gravada.
-- ------------------------------------------------------------

create or replace function public.arena_resolver_rodada(
    p_batalha_id uuid,
    p_rodada_esperada integer,
    p_carta_boss text,
    p_carta_frota_1 text,
    p_carta_frota_2 text,
    p_resumo jsonb,
    p_estado_antes jsonb,
    p_estado_depois jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_batalha public.arena_batalhas%rowtype;
    v_nome text;
begin
    if auth.uid() is null then
        raise exception 'É necessário estar autenticado.';
    end if;

    select * into v_batalha
    from public.arena_batalhas
    where id = p_batalha_id
    for update;

    if not found then
        raise exception 'Batalha não encontrada.';
    end if;

    if v_batalha.status <> 'em_andamento' then
        raise exception 'A batalha não está em andamento.';
    end if;

    if v_batalha.rodada_atual <> p_rodada_esperada then
        raise exception 'Conflito: a rodada já foi alterada por outra pessoa.'
            using errcode = '40001';
    end if;

    if p_carta_boss not in ('A','2','3','4','5','6','7','8','9','10','J','Q','K')
       or p_carta_frota_1 not in ('A','2','3','4','5','6','7','8','9','10','J','Q','K')
       or p_carta_frota_2 not in ('A','2','3','4','5','6','7','8','9','10','J','Q','K') then
        raise exception 'Uma das cartas informadas é inválida.';
    end if;

    v_nome := coalesce(public.arena_nome_usuario(auth.uid()), 'Tripulante');

    insert into public.arena_rodadas (
        batalha_id,
        numero,
        carta_boss,
        carta_frota_1,
        carta_frota_2,
        resumo,
        estado_antes,
        estado_depois,
        registrado_por,
        registrado_por_nome
    ) values (
        p_batalha_id,
        p_rodada_esperada,
        p_carta_boss,
        p_carta_frota_1,
        p_carta_frota_2,
        coalesce(p_resumo, '{}'::jsonb),
        p_estado_antes,
        p_estado_depois,
        auth.uid(),
        v_nome
    );

    update public.arena_batalhas
    set estado = p_estado_depois,
        rodada_atual = p_rodada_esperada + 1,
        atualizado_em = now()
    where id = p_batalha_id;

    return jsonb_build_object(
        'batalha_id', p_batalha_id,
        'rodada_atual', p_rodada_esperada + 1,
        'atualizado_em', now(),
        'registrado_por_nome', v_nome
    );
end;
$$;

-- ------------------------------------------------------------
-- 6. DESFAZER A ÚLTIMA RODADA ATOMICAMENTE
-- ------------------------------------------------------------

create or replace function public.arena_desfazer_rodada(p_batalha_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_batalha public.arena_batalhas%rowtype;
    v_rodada public.arena_rodadas%rowtype;
begin
    if auth.uid() is null then
        raise exception 'É necessário estar autenticado.';
    end if;

    select * into v_batalha
    from public.arena_batalhas
    where id = p_batalha_id
    for update;

    if not found then
        raise exception 'Batalha não encontrada.';
    end if;

    select * into v_rodada
    from public.arena_rodadas
    where batalha_id = p_batalha_id
    order by numero desc
    limit 1
    for update;

    if not found then
        raise exception 'Não existe rodada para desfazer.';
    end if;

    delete from public.arena_rodadas where id = v_rodada.id;

    update public.arena_batalhas
    set estado = v_rodada.estado_antes,
        rodada_atual = v_rodada.numero,
        atualizado_em = now()
    where id = p_batalha_id;

    return jsonb_build_object(
        'batalha_id', p_batalha_id,
        'rodada_atual', v_rodada.numero,
        'estado', v_rodada.estado_antes,
        'atualizado_em', now()
    );
end;
$$;

revoke all on function public.arena_resolver_rodada(uuid, integer, text, text, text, jsonb, jsonb, jsonb) from public;
revoke all on function public.arena_desfazer_rodada(uuid) from public;

grant execute on function public.arena_resolver_rodada(uuid, integer, text, text, text, jsonb, jsonb, jsonb) to authenticated;
grant execute on function public.arena_desfazer_rodada(uuid) to authenticated;

grant select, insert, update on public.arena_batalhas to authenticated;
grant select on public.arena_rodadas to authenticated;

-- Atualizações em tempo real da tabela arena_batalhas.
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'arena_batalhas'
    ) then
        execute 'alter publication supabase_realtime add table public.arena_batalhas';
    end if;
end;
$$;
