-- Execute esta versão completa no SQL Editor do Supabase.
-- É seguro rodá-la novamente se a versão antiga já foi instalada.
-- Pré-requisito: o arquivo supabase-integridade.sql já deve ter sido executado.
--
-- A senha é validada dentro do banco. O navegador nunca altera diretamente
-- a integridade: o disparo usa uma operação atômica e registra o tripulante.

alter table public.nave_integridade
    add column if not exists ultimo_disparo timestamptz,
    add column if not exists ultimo_disparo_usuario_id uuid
        references auth.users(id) on delete set null,
    add column if not exists ultimo_disparo_usuario_nome text;

create table if not exists public.nave_torre_armas_historico (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users(id) on delete set null,
    usuario_nome text not null,
    valor_anterior integer not null,
    valor_novo integer not null,
    reserva_anterior integer not null default 0,
    reserva_nova integer not null default 0,
    origem_consumo text not null default 'integridade',
    disparado_em timestamptz not null default now()
);

alter table public.nave_torre_armas_historico
    add column if not exists reserva_anterior integer not null default 0,
    add column if not exists reserva_nova integer not null default 0,
    add column if not exists origem_consumo text not null default 'integridade';

alter table public.nave_torre_armas_historico enable row level security;

revoke insert, update, delete
on public.nave_torre_armas_historico
from authenticated;

grant select
on public.nave_torre_armas_historico
to authenticated;

drop policy if exists "Tripulantes podem ver disparos da torre"
on public.nave_torre_armas_historico;

create policy "Tripulantes podem ver disparos da torre"
on public.nave_torre_armas_historico
for select
to authenticated
using (true);

create or replace function public.validar_senha_torre_armas(p_senha text)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
    select auth.uid() is not null and p_senha = '0000';
$$;

create or replace function public.disparar_torre_armas(p_senha text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_usuario_id uuid := auth.uid();
    v_usuario_nome text;
    v_estado public.nave_integridade%rowtype;
    v_valor_anterior integer;
    v_reserva_anterior integer;
    v_origem_consumo text;
    v_agora timestamptz := clock_timestamp();
begin
    if v_usuario_id is null then
        raise exception 'Usuário não autenticado';
    end if;

    if p_senha is distinct from '0000' then
        raise exception 'Senha da Torre de Armas inválida';
    end if;

    select coalesce(
        nullif(trim(nome), ''),
        nullif(trim(username), ''),
        'Tripulante'
    )
    into v_usuario_nome
    from public.profiles
    where id = v_usuario_id;

    v_usuario_nome := coalesce(v_usuario_nome, 'Tripulante');

    select *
    into v_estado
    from public.nave_integridade
    where id = 1
    for update;

    if not found then
        raise exception 'Estado de integridade não encontrado';
    end if;

    if v_estado.valor <= 0 and v_estado.reserva_extra <= 0 then
        return jsonb_build_object(
            'sucesso', false,
            'codigo', 'sem_integridade',
            'valor', v_estado.valor,
            'maximo', v_estado.maximo,
            'reserva_extra', v_estado.reserva_extra,
            'ultimo_disparo', v_estado.ultimo_disparo,
            'ultimo_disparo_usuario_nome',
                v_estado.ultimo_disparo_usuario_nome
        );
    end if;

    v_valor_anterior := v_estado.valor;
    v_reserva_anterior := v_estado.reserva_extra;
    v_origem_consumo := case
        when v_estado.reserva_extra > 0 then 'reserva_extra'
        else 'integridade'
    end;

    update public.nave_integridade
    set valor = case
            when reserva_extra > 0 then valor
            else valor - 1
        end,
        reserva_extra = case
            when reserva_extra > 0 then reserva_extra - 1
            else reserva_extra
        end,
        ultimo_disparo = v_agora,
        ultimo_disparo_usuario_id = v_usuario_id,
        ultimo_disparo_usuario_nome = v_usuario_nome,
        atualizado_em = v_agora
    where id = 1
    returning * into v_estado;

    insert into public.nave_torre_armas_historico (
        usuario_id,
        usuario_nome,
        valor_anterior,
        valor_novo,
        reserva_anterior,
        reserva_nova,
        origem_consumo,
        disparado_em
    ) values (
        v_usuario_id,
        v_usuario_nome,
        v_valor_anterior,
        v_estado.valor,
        v_reserva_anterior,
        v_estado.reserva_extra,
        v_origem_consumo,
        v_agora
    );

    return jsonb_build_object(
        'sucesso', true,
        'codigo', case
            when v_origem_consumo = 'reserva_extra' then 'disparado_reserva'
            else 'disparado'
        end,
        'valor', v_estado.valor,
        'maximo', v_estado.maximo,
        'reserva_extra', v_estado.reserva_extra,
        'origem_consumo', v_origem_consumo,
        'ultimo_disparo', v_estado.ultimo_disparo,
        'ultimo_disparo_usuario_nome',
            v_estado.ultimo_disparo_usuario_nome
    );
end;
$$;

revoke all on function public.validar_senha_torre_armas(text) from public;
revoke all on function public.disparar_torre_armas(text) from public;

grant execute on function public.validar_senha_torre_armas(text)
to authenticated;

grant execute on function public.disparar_torre_armas(text)
to authenticated;
